# Simple generator for ui_images_auto.h
# Inputs: IMAGES_DIR, OUTPUT_FILE

if(NOT DEFINED IMAGES_DIR)
  message(FATAL_ERROR "IMAGES_DIR not set")
endif()
if(NOT DEFINED OUTPUT_FILE)
  message(FATAL_ERROR "OUTPUT_FILE not set")
endif()

file(WRITE "${OUTPUT_FILE}" "// Auto-generated by generate_images.cmake\n")
file(APPEND "${OUTPUT_FILE}" "#pragma once\n\n")
file(GLOB IMAGE_CS "${IMAGES_DIR}/*.c")
foreach(C_FILE ${IMAGE_CS})
  get_filename_component(NAME_WE "${C_FILE}" NAME_WE)
  # The SquareLine files typically define: lv_image_dsc_t ui_img_<name>;
  file(APPEND "${OUTPUT_FILE}" "extern lv_image_dsc_t ui_img_${NAME_WE};\n")
endforeach()