// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
lv_anim_t * Imagezoom_Animation(lv_obj_t * TargetObject, int delay);


// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
lv_anim_t * Imagezoom_Animation(lv_obj_t * TargetObject, int delay)
{
    lv_anim_t * out_anim;
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_malloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_image_zoom);
    lv_anim_set_values(&PropertyAnimation_0, 200, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_set_get_value_cb(&PropertyAnimation_0, &_ui_anim_callback_get_image_zoom);
    out_anim = lv_anim_start(&PropertyAnimation_0);

    return out_anim;
}

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_display_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Memu_screen_init();
    ui_WakeMode_screen_init();
    ui_AlarmOFF_screen_init();
    ui_AlarmON_screen_init();
    ui_Volume__screen_init();
    ui_UnwindSelet_screen_init();
    ui_UnwindOn_screen_init();
    ui_NoiseTime_screen_init();
    ui_Light_screen_init();
    ui_SetTime_screen_init();
    ui_MorningAnimation_screen_init();
    ui_BluetoothMusic_screen_init();
    ui_OTA_screen_init();
    ui_sleepData_screen_init();

    //其他文件的初始化代码
    ui_NetworkBoot_screen_init();
    ui_Connecting_screen_init();
    ui_ConnectingSuccess_screen_init();
    ui_ConnectingFailed_screen_init();
    ui_OfflineMode_screen_init();

    ui_Boot_screen_init();
    ui_Detection_screen_init();
    ui_DetectionY_screen_init();
    ui_DetectionN_screen_init();
    ui_DetectionN1_screen_init();
    ui_MianNoPerson_screen_init();
    ui_MianYesPerson_screen_init();

    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Boot);
}

void ui_destroy(void)
{
    ui_Memu_screen_destroy();
    ui_WakeMode_screen_destroy();
    ui_AlarmOFF_screen_destroy();
    ui_AlarmON_screen_destroy();
    ui_Volume__screen_destroy();
    ui_UnwindSelet_screen_destroy();
    ui_UnwindOn_screen_destroy();
    ui_NoiseTime_screen_destroy();
    ui_Light_screen_destroy();
    ui_SetTime_screen_destroy();
    ui_MorningAnimation_screen_destroy();
    ui_BluetoothMusic_screen_destroy();
    ui_OTA_screen_destroy();
    ui_sleepData_screen_destroy();
    //其他文件的销毁代码
    ui_NetworkBoot_screen_destroy();
    ui_Connecting_screen_destroy();
    ui_ConnectingSuccess_screen_destroy();
    ui_ConnectingFailed_screen_destroy();
    ui_OfflineMode_screen_destroy();

    ui_Boot_screen_destroy();
    ui_Detection_screen_destroy();
    ui_DetectionY_screen_destroy();
    ui_DetectionN_screen_destroy();
    ui_DetectionN1_screen_destroy();
    ui_MianNoPerson_screen_destroy();
    ui_MianYesPerson_screen_destroy();

}
