// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef _LVGL_FUNCTION1_UI_H
#define _LVGL_FUNCTION1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Memu.h"
#include "screens/ui_WakeMode.h"
#include "screens/ui_AlarmOFF.h"
#include "screens/ui_AlarmON.h"
#include "screens/ui_Volume_.h"
#include "screens/ui_UnwindSelet.h"
#include "screens/ui_UnwindOn.h"
#include "screens/ui_NoiseTime.h"
#include "screens/ui_Light.h"
#include "screens/ui_SetTime.h"
#include "screens/ui_MorningAnimation.h"
#include "screens/ui_BluetoothMusic.h"
#include "screens/ui_OTA.h"
#include "screens/ui_sleepData.h"

//satrt文件
#include "screens/ui_Boot.h"
#include "screens/ui_Detection.h"
#include "screens/ui_DetectionY.h"
#include "screens/ui_DetectionN.h"
#include "screens/ui_DetectionN1.h"
#include "screens/ui_MianNoPerson.h"
#include "screens/ui_MianYesPerson.h"

//网络相关屏幕
#include "screens/ui_NetworkBoot.h"
#include "screens/ui_Connecting.h"
#include "screens/ui_ConnectingSuccess.h"
#include "screens/ui_ConnectingFailed.h"
#include "screens/ui_OfflineMode.h"


///////////////////// VARIABLES ////////////////////

extern lv_anim_t * Imagezoom_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
// 图片声明已自动生成，请查看 ui_images_auto.h
// Image declarations are auto-generated, see ui_images_auto.h
#include "ui_images_auto.h"

// FONTS
LV_FONT_DECLARE(ui_font_sfprodisplay14);
LV_FONT_DECLARE(ui_font_sfprodisplay18);
LV_FONT_DECLARE(ui_font_sfprodisplay20);
LV_FONT_DECLARE(ui_font_sfprodisplay24);
LV_FONT_DECLARE(ui_font_sfprodisplay36);
LV_FONT_DECLARE(ui_font_sfprodisplay45);
LV_FONT_DECLARE(ui_font_sfprodisplay60);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
