// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef _LVGL_FUNCTION1_UI_COMP_HOOK_H
#define _LVGL_FUNCTION1_UI_COMP_HOOK_H

#ifdef __cplusplus
extern "C" {
#endif

void ui_comp_demo_create_hook(lv_obj_t * comp);
void ui_comp_Image_create_hook(lv_obj_t * comp);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
