// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef _UI_COMP_DEMO_H
#define _UI_COMP_DEMO_H

#include "../ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT demo
#define UI_COMP_DEMO_DEMO 0
#define _UI_COMP_DEMO_NUM 1
lv_obj_t * ui_demo_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
