// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

// COMPONENT Image

lv_obj_t * ui_Image_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Image;
    cui_Image = lv_image_create(comp_parent);
    lv_image_set_src(cui_Image, &ui_img_bootimage_png);
    lv_obj_set_width(cui_Image, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(cui_Image, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_align(cui_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_Image, 169);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_IMAGE_NUM);
    children[UI_COMP_IMAGE_IMAGE] = cui_Image;
    lv_obj_add_event_cb(cui_Image, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Image, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_Image_create_hook(cui_Image);
    return cui_Image;
}

