// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

// COMPONENT demo

lv_obj_t * ui_demo_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_demo;
    cui_demo = lv_image_create(comp_parent);
    lv_image_set_src(cui_demo, &ui_img_bootimage_png);
    lv_obj_set_width(cui_demo, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(cui_demo, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_align(cui_demo, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_demo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(cui_demo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(cui_demo, 169);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_DEMO_NUM);
    children[UI_COMP_DEMO_DEMO] = cui_demo;
    lv_obj_add_event_cb(cui_demo, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_demo, del_component_child_event_cb, LV_EVENT_DELETE, children);
    ui_comp_demo_create_hook(cui_demo);
    return cui_demo;
}

