// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_ALARMOFF_H
#define UI_ALARMOFF_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AlarmOFF
extern void ui_AlarmOFF_screen_init(void);
extern void ui_AlarmOFF_screen_destroy(void);
extern void ui_AlarmOFF_screen_relocalize(void);
extern lv_obj_t * ui_AlarmOFF;
extern lv_obj_t * ui_AlarmOFFContainer;
extern lv_obj_t * ui_AlarmOFFLabel1;
extern lv_obj_t * ui_AlarmOFFLabel2;
extern lv_obj_t * ui_AlarmOFFImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

