// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_AlarmOFF = NULL;
lv_obj_t * ui_AlarmOFFContainer = NULL;
lv_obj_t * ui_AlarmOFFLabel1 = NULL;
lv_obj_t * ui_AlarmOFFLabel2 = NULL;
lv_obj_t * ui_AlarmOFFImage = NULL;
// event funtions

// build funtions

void ui_AlarmOFF_screen_init(void)
{
    ui_AlarmOFF = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AlarmOFF, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AlarmOFF, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmOFF, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmOFF, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmOFFContainer = lv_obj_create(ui_AlarmOFF);
    lv_obj_remove_style_all(ui_AlarmOFFContainer);
    lv_obj_set_width(ui_AlarmOFFContainer, 300);
    lv_obj_set_height(ui_AlarmOFFContainer, 300);
    lv_obj_set_align(ui_AlarmOFFContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AlarmOFFContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmOFFContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmOFFLabel1 = lv_label_create(ui_AlarmOFFContainer);
    lv_obj_set_width(ui_AlarmOFFLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmOFFLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmOFFLabel1, 0);
    lv_obj_set_y(ui_AlarmOFFLabel1, 60);
    lv_obj_set_align(ui_AlarmOFFLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmOFFLabel1, "Rotate to Set Alarm\n");
    lv_obj_set_style_text_color(ui_AlarmOFFLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmOFFLabel1, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_AlarmOFFLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmOFFLabel1, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmOFFLabel2 = lv_label_create(ui_AlarmOFFContainer);
    lv_obj_set_width(ui_AlarmOFFLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmOFFLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmOFFLabel2, 0);
    lv_obj_set_y(ui_AlarmOFFLabel2, 10);
    lv_obj_set_align(ui_AlarmOFFLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmOFFLabel2, "No Alarm");
    lv_obj_set_style_text_color(ui_AlarmOFFLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmOFFLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmOFFLabel2, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmOFFImage = lv_image_create(ui_AlarmOFFContainer);
    lv_image_set_src(ui_AlarmOFFImage, &ui_img_clock_png);
    lv_obj_set_width(ui_AlarmOFFImage, LV_SIZE_CONTENT);   /// 102
    lv_obj_set_height(ui_AlarmOFFImage, LV_SIZE_CONTENT);    /// 99
    lv_obj_set_x(ui_AlarmOFFImage, 0);
    lv_obj_set_y(ui_AlarmOFFImage, -60);
    lv_obj_set_align(ui_AlarmOFFImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmOFFImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AlarmOFFImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_AlarmOFFImage, 179);

}

void ui_AlarmOFF_screen_destroy(void)
{
    if(ui_AlarmOFF) lv_obj_del(ui_AlarmOFF);

    // NULL screen variables
    ui_AlarmOFF = NULL;
    ui_AlarmOFFContainer = NULL;
    ui_AlarmOFFLabel1 = NULL;
    ui_AlarmOFFLabel2 = NULL;
    ui_AlarmOFFImage = NULL;

}
