// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_AlarmON = NULL;
lv_obj_t * ui_AlarmONContainer = NULL;
lv_obj_t * ui_AlarmONLabel1 = NULL;
lv_obj_t * ui_AlarmONImage = NULL;
lv_obj_t * ui_AlarmONhour = NULL;
lv_obj_t * ui_AlarmONminute = NULL;
lv_obj_t * ui_AlarmONLabel2 = NULL;
// event funtions

// build funtions

void ui_AlarmON_screen_init(void)
{
    ui_AlarmON = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_AlarmON, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_AlarmON, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AlarmON, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmON, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmONContainer = lv_obj_create(ui_AlarmON);
    lv_obj_remove_style_all(ui_AlarmONContainer);
    lv_obj_set_width(ui_AlarmONContainer, 300);
    lv_obj_set_height(ui_AlarmONContainer, 300);
    lv_obj_set_align(ui_AlarmONContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AlarmONContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_AlarmONContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmONLabel1 = lv_label_create(ui_AlarmONContainer);
    lv_obj_set_width(ui_AlarmONLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmONLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmONLabel1, 0);
    lv_obj_set_y(ui_AlarmONLabel1, -85);
    lv_obj_set_align(ui_AlarmONLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmONLabel1, "AM");
    lv_obj_set_style_text_color(ui_AlarmONLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmONLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmONLabel1, &ui_font_sfprodisplay36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmONImage = lv_image_create(ui_AlarmONContainer);
    lv_image_set_src(ui_AlarmONImage, &ui_img_800502611);
    lv_obj_set_width(ui_AlarmONImage, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_AlarmONImage, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_align(ui_AlarmONImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AlarmONImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_AlarmONImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AlarmONhour = lv_label_create(ui_AlarmONContainer);
    lv_obj_set_width(ui_AlarmONhour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmONhour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmONhour, -60);
    lv_obj_set_y(ui_AlarmONhour, 0);
    lv_obj_set_align(ui_AlarmONhour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmONhour, "07");
    lv_obj_set_style_text_color(ui_AlarmONhour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmONhour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmONhour, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmONminute = lv_label_create(ui_AlarmONContainer);
    lv_obj_set_width(ui_AlarmONminute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmONminute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmONminute, 60);
    lv_obj_set_y(ui_AlarmONminute, 0);
    lv_obj_set_align(ui_AlarmONminute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmONminute, "30");
    lv_obj_set_style_text_color(ui_AlarmONminute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmONminute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_AlarmONminute, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AlarmONLabel2 = lv_label_create(ui_AlarmONContainer);
    lv_obj_set_width(ui_AlarmONLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AlarmONLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_AlarmONLabel2, 0);
    lv_obj_set_y(ui_AlarmONLabel2, 70);
    lv_obj_set_align(ui_AlarmONLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AlarmONLabel2, "Hold to Cancel");
    lv_obj_set_style_text_color(ui_AlarmONLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_AlarmONLabel2, 170, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_AlarmON_screen_destroy(void)
{
    if(ui_AlarmON) lv_obj_del(ui_AlarmON);

    // NULL screen variables
    ui_AlarmON = NULL;
    ui_AlarmONContainer = NULL;
    ui_AlarmONLabel1 = NULL;
    ui_AlarmONImage = NULL;
    ui_AlarmONhour = NULL;
    ui_AlarmONminute = NULL;
    ui_AlarmONLabel2 = NULL;

}

void ui_AlarmON_screen_relocalize(void)
{
    // label widgets on screen

}
