// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_ALARMON_H
#define UI_ALARMON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AlarmON

extern void ui_AlarmON_screen_init(void);
extern void ui_AlarmON_screen_destroy(void);
extern lv_obj_t * ui_AlarmON;
extern lv_obj_t * ui_AlarmONContainer;
extern lv_obj_t * ui_AlarmONLabel1;
extern lv_obj_t * ui_AlarmONImage;
extern lv_obj_t * ui_AlarmONhour;
extern lv_obj_t * ui_AlarmONminute;
extern lv_obj_t * ui_AlarmONLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

