// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_BluetoothMusic = NULL;
lv_obj_t * ui_BluetoothMusicLabel1 = NULL;
lv_obj_t * ui_BluetoothMusicLabel2 = NULL;
// event funtions

// build funtions

void ui_BluetoothMusic_screen_init(void)
{
    ui_BluetoothMusic = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_BluetoothMusic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BluetoothMusic, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BluetoothMusic, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BluetoothMusic, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothMusicLabel1 = lv_label_create(ui_BluetoothMusic);
    lv_obj_set_width(ui_BluetoothMusicLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BluetoothMusicLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BluetoothMusicLabel1, 0);
    lv_obj_set_y(ui_BluetoothMusicLabel1, -25);
    lv_obj_set_align(ui_BluetoothMusicLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BluetoothMusicLabel1, "Track Title");
    lv_obj_set_style_text_color(ui_BluetoothMusicLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BluetoothMusicLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BluetoothMusicLabel1, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BluetoothMusicLabel2 = lv_label_create(ui_BluetoothMusic);
    lv_obj_set_width(ui_BluetoothMusicLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BluetoothMusicLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BluetoothMusicLabel2, 0);
    lv_obj_set_y(ui_BluetoothMusicLabel2, 20);
    lv_obj_set_align(ui_BluetoothMusicLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BluetoothMusicLabel2, "Artist Name");
    lv_obj_set_style_text_color(ui_BluetoothMusicLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BluetoothMusicLabel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BluetoothMusicLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_BluetoothMusic_screen_destroy(void)
{
    if(ui_BluetoothMusic) lv_obj_del(ui_BluetoothMusic);

    // NULL screen variables
    ui_BluetoothMusic = NULL;
    ui_BluetoothMusicLabel1 = NULL;
    ui_BluetoothMusicLabel2 = NULL;

}

void ui_BluetoothMusic_screen_relocalize(void)
{
    // label widgets on screen

}
