// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_BLUETOOTHMUSIC_H
#define UI_BLUETOOTHMUSIC_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BluetoothMusic
extern void ui_BluetoothMusic_screen_init(void);
extern void ui_BluetoothMusic_screen_destroy(void);
extern void ui_BluetoothMusic_screen_relocalize(void);
extern lv_obj_t * ui_BluetoothMusic;
extern lv_obj_t * ui_BluetoothMusicLabel1;
extern lv_obj_t * ui_BluetoothMusicLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

