// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_Boot = NULL;
lv_obj_t * ui_BootImage = NULL;
lv_obj_t * ui_BootLabel = NULL;
// event funtions


// build funtions

void ui_Boot_screen_init(void)
{
    ui_Boot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Boot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Boot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Boot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BootImage = lv_image_create(ui_Boot);
    lv_image_set_src(ui_BootImage, &ui_img_component_8_png);
    lv_obj_set_width(ui_BootImage, LV_SIZE_CONTENT);   /// 149
    lv_obj_set_height(ui_BootImage, LV_SIZE_CONTENT);    /// 122
    lv_obj_set_x(ui_BootImage, 0);
    lv_obj_set_y(ui_BootImage, -28);
    lv_obj_set_align(ui_BootImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BootImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_BootImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_BootImage, 168);

    ui_BootLabel = lv_label_create(ui_Boot);
    lv_obj_set_width(ui_BootLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BootLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BootLabel, 0);
    lv_obj_set_y(ui_BootLabel, 50);
    lv_obj_set_align(ui_BootLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BootLabel, "Lunawake");
    lv_obj_set_style_text_color(ui_BootLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BootLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BootLabel, &ui_font_sfprodisplay36, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Boot_screen_destroy(void)
{
    if(ui_Boot) lv_obj_del(ui_Boot);

    // NULL screen variables
    ui_Boot = NULL;
    ui_BootImage = NULL;
    ui_BootLabel = NULL;

}
