// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_BOOT_H
#define UI_BOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Boot
extern void ui_Boot_screen_init(void);
extern void ui_Boot_screen_destroy(void);
extern void ui_Boot_screen_relocalize(void);
extern lv_obj_t * ui_Boot;
extern lv_obj_t * ui_BootImage;
extern lv_obj_t * ui_BootLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

