// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#ifndef UI_CONNECTINGFAILED_H
#define UI_CONNECTINGFAILED_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConnectingFailed
extern void ui_ConnectingFailed_screen_init(void);
extern void ui_ConnectingFailed_screen_destroy(void);
extern lv_obj_t * ui_ConnectingFailed;
extern lv_obj_t * ui_ConnectingFailedContainer;
extern lv_obj_t * ui_ConnectingFailedLabel1;
extern lv_obj_t * ui_ConnectingFailedImage;
extern lv_obj_t * ui_ConnectingFailedLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

