// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#include "../ui.h"

lv_obj_t * ui_ConnectingSuccess = NULL;
lv_obj_t * ui_ConnectingSuccessContainer = NULL;
lv_obj_t * ui_ConnectingSuccessLabel = NULL;
lv_obj_t * ui_ConnectingSuccessImage = NULL;
// event funtions


// build funtions

void ui_ConnectingSuccess_screen_init(void)
{
    ui_ConnectingSuccess = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConnectingSuccess, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnectingSuccess, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectingSuccess, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingSuccessContainer = lv_obj_create(ui_ConnectingSuccess);
    lv_obj_remove_style_all(ui_ConnectingSuccessContainer);
    lv_obj_set_width(ui_ConnectingSuccessContainer, 290);
    lv_obj_set_height(ui_ConnectingSuccessContainer, 290);
    lv_obj_set_align(ui_ConnectingSuccessContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConnectingSuccessContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConnectingSuccessContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConnectingSuccessContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConnectingSuccessContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectingSuccessContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingSuccessLabel = lv_label_create(ui_ConnectingSuccessContainer);
    lv_obj_set_width(ui_ConnectingSuccessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectingSuccessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectingSuccessLabel, 0);
    lv_obj_set_y(ui_ConnectingSuccessLabel, 35);
    lv_obj_set_align(ui_ConnectingSuccessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectingSuccessLabel, "Wi-Fi Connected");
    lv_obj_set_style_text_color(ui_ConnectingSuccessLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectingSuccessLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConnectingSuccessLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectingSuccessLabel, &ui_font_sfprodisplay20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingSuccessImage = lv_image_create(ui_ConnectingSuccessContainer);
    lv_image_set_src(ui_ConnectingSuccessImage, &ui_img_vector_png);
    lv_obj_set_width(ui_ConnectingSuccessImage, LV_SIZE_CONTENT);   /// 93
    lv_obj_set_height(ui_ConnectingSuccessImage, LV_SIZE_CONTENT);    /// 94
    lv_obj_set_x(ui_ConnectingSuccessImage, 0);
    lv_obj_set_y(ui_ConnectingSuccessImage, -30);
    lv_obj_set_align(ui_ConnectingSuccessImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectingSuccessImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ConnectingSuccessImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ConnectingSuccessImage, 159);

}

void ui_ConnectingSuccess_screen_destroy(void)
{
    if(ui_ConnectingSuccess) lv_obj_del(ui_ConnectingSuccess);

    // NULL screen variables
    ui_ConnectingSuccess = NULL;
    ui_ConnectingSuccessContainer = NULL;
    ui_ConnectingSuccessLabel = NULL;
    ui_ConnectingSuccessImage = NULL;

}
