// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#include "../ui.h"

lv_obj_t * ui_ConnectingFailed = NULL;
lv_obj_t * ui_ConnectingFailedContainer = NULL;
lv_obj_t * ui_ConnectingFailedLabel1 = NULL;
lv_obj_t * ui_ConnectingFailedImage = NULL;
lv_obj_t * ui_ConnectingFailedLabel2 = NULL;
// event funtions

// build funtions

void ui_ConnectingFailed_screen_init(void)
{
    ui_ConnectingFailed = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ConnectingFailed, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ConnectingFailed, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ConnectingFailed, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingFailedContainer = lv_obj_create(ui_ConnectingFailed);
    lv_obj_remove_style_all(ui_ConnectingFailedContainer);
    lv_obj_set_width(ui_ConnectingFailedContainer, 290);
    lv_obj_set_height(ui_ConnectingFailedContainer, 290);
    lv_obj_set_align(ui_ConnectingFailedContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConnectingFailedContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ConnectingFailedContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ConnectingFailedContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ConnectingFailedContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ConnectingFailedContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingFailedLabel1 = lv_label_create(ui_ConnectingFailedContainer);
    lv_obj_set_width(ui_ConnectingFailedLabel1, LV_SIZE_CONTENT);   /// 68
    lv_obj_set_height(ui_ConnectingFailedLabel1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_ConnectingFailedLabel1, 0);
    lv_obj_set_y(ui_ConnectingFailedLabel1, 10);
    lv_obj_set_align(ui_ConnectingFailedLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectingFailedLabel1, "No Internet Connection");
    lv_obj_set_style_text_color(ui_ConnectingFailedLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectingFailedLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConnectingFailedLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectingFailedLabel1, &ui_font_sfprodisplay20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingFailedImage = lv_image_create(ui_ConnectingFailedContainer);
    lv_image_set_src(ui_ConnectingFailedImage, &ui_img_wifino_png);
    lv_obj_set_width(ui_ConnectingFailedImage, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ConnectingFailedImage, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ConnectingFailedImage, 0);
    lv_obj_set_y(ui_ConnectingFailedImage, -45);
    lv_obj_set_align(ui_ConnectingFailedImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectingFailedImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ConnectingFailedImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectingFailedLabel2 = lv_label_create(ui_ConnectingFailedContainer);
    lv_obj_set_width(ui_ConnectingFailedLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectingFailedLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectingFailedLabel2, 0);
    lv_obj_set_y(ui_ConnectingFailedLabel2, 60);
    lv_obj_set_align(ui_ConnectingFailedLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectingFailedLabel2, "Press button to retry  \nHold to enter Offline Mode");
    lv_obj_set_style_text_color(ui_ConnectingFailedLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectingFailedLabel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConnectingFailedLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectingFailedLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ConnectingFailed_screen_destroy(void)
{
    if(ui_ConnectingFailed) lv_obj_del(ui_ConnectingFailed);

    // NULL screen variables
    ui_ConnectingFailed = NULL;
    ui_ConnectingFailedContainer = NULL;
    ui_ConnectingFailedLabel1 = NULL;
    ui_ConnectingFailedImage = NULL;
    ui_ConnectingFailedLabel2 = NULL;

}

void ui_ConnectingFailed_screen_relocalize(void)
{
    // label widgets on screen

}
