// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#include "../ui.h"

lv_obj_t * ui_Connecting = NULL;
lv_obj_t * ui_ConnectingContainer = NULL;
lv_obj_t * ui_ConnectingLabel = NULL;
lv_obj_t * ui_ConnectingImage = NULL;
// event funtions

// build funtions

void ui_Connecting_screen_init(void)
{
    ui_Connecting = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Connecting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Connecting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Connecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingContainer = lv_obj_create(ui_Connecting);
    lv_obj_remove_style_all(ui_ConnectingContainer);
    lv_obj_set_width(ui_ConnectingContainer, 290);
    lv_obj_set_height(ui_ConnectingContainer, 290);
    lv_obj_set_align(ui_ConnectingContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ConnectingContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ConnectingLabel = lv_label_create(ui_ConnectingContainer);
    lv_obj_set_width(ui_ConnectingLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ConnectingLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ConnectingLabel, 0);
    lv_obj_set_y(ui_ConnectingLabel, 35);
    lv_obj_set_align(ui_ConnectingLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ConnectingLabel, " Connecting to \nNetwork");
    lv_obj_set_style_text_color(ui_ConnectingLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ConnectingLabel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ConnectingLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ConnectingLabel, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ConnectingImage = lv_image_create(ui_ConnectingContainer);
    lv_image_set_src(ui_ConnectingImage, &ui_img_1757982151);
    lv_obj_set_width(ui_ConnectingImage, LV_SIZE_CONTENT);   /// 128
    lv_obj_set_height(ui_ConnectingImage, LV_SIZE_CONTENT);    /// 128
    lv_obj_set_x(ui_ConnectingImage, 0);
    lv_obj_set_y(ui_ConnectingImage, -30);
    lv_obj_set_align(ui_ConnectingImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ConnectingImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ConnectingImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_ConnectingImage, 159);

}

void ui_Connecting_screen_destroy(void)
{
    if(ui_Connecting) lv_obj_del(ui_Connecting);

    // NULL screen variables
    ui_Connecting = NULL;
    ui_ConnectingContainer = NULL;
    ui_ConnectingLabel = NULL;
    ui_ConnectingImage = NULL;

}

void ui_Connecting_screen_relocalize(void)
{
    // label widgets on screen

}
