// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#ifndef UI_CONNECTING_H
#define UI_CONNECTING_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connecting
extern void ui_Connecting_screen_init(void);
extern void ui_Connecting_screen_destroy(void);
extern void ui_Connecting_screen_relocalize(void);
extern lv_obj_t * ui_Connecting;
extern lv_obj_t * ui_ConnectingContainer;
extern lv_obj_t * ui_ConnectingLabel;
extern lv_obj_t * ui_ConnectingImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

