// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#ifndef UI_CONNECTINGSUCCESS_H
#define UI_CONNECTINGSUCCESS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ConnectingSuccess
extern void ui_ConnectingSuccess_screen_init(void);
extern void ui_ConnectingSuccess_screen_destroy(void);
extern void ui_ConnectingSuccess_screen_relocalize(void);
extern lv_obj_t * ui_ConnectingSuccess;
extern lv_obj_t * ui_ConnectingSuccessContainer;
extern lv_obj_t * ui_ConnectingSuccessLabel;
extern lv_obj_t * ui_ConnectingSuccessImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

