// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_DETECTION_H
#define UI_DETECTION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Detection
extern void ui_Detection_screen_init(void);
extern void ui_Detection_screen_destroy(void);
extern void ui_Detection_screen_relocalize(void);
extern lv_obj_t * ui_Detection;
extern lv_obj_t * ui_DetectionContainer;
extern lv_obj_t * ui_DetectionLabel;
extern lv_obj_t * ui_DetectionImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

