// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_DetectionN = NULL;
lv_obj_t * ui_DetectionNContainer = NULL;
lv_obj_t * ui_DetectionNLabel = NULL;
lv_obj_t * ui_DetectionNImage = NULL;
// event funtions



// build funtions

void ui_DetectionN_screen_init(void)
{
    ui_DetectionN = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DetectionN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DetectionN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DetectionN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionNContainer = lv_obj_create(ui_DetectionN);
    lv_obj_remove_style_all(ui_DetectionNContainer);
    lv_obj_set_width(ui_DetectionNContainer, 290);
    lv_obj_set_height(ui_DetectionNContainer, 290);
    lv_obj_set_align(ui_DetectionNContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DetectionNContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DetectionNContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DetectionNContainer, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DetectionNContainer, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DetectionNContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_DetectionNContainer, lv_color_hex(0xE7C1C1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_DetectionNContainer, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionNLabel = lv_label_create(ui_DetectionNContainer);
    lv_obj_set_width(ui_DetectionNLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DetectionNLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DetectionNLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DetectionNLabel, "I didn‘t sense anyone\n nearby");
    lv_obj_set_style_text_color(ui_DetectionNLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DetectionNLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DetectionNLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DetectionNLabel, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionNImage = lv_image_create(ui_DetectionNContainer);
    lv_image_set_src(ui_DetectionNImage, &ui_img_component_29_png);
    lv_obj_set_width(ui_DetectionNImage, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_DetectionNImage, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_DetectionNImage, 113);
    lv_obj_set_y(ui_DetectionNImage, -44);
    lv_obj_set_align(ui_DetectionNImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DetectionNImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DetectionNImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_rotation(ui_DetectionNImage, 70);
    lv_image_set_scale(ui_DetectionNImage, 169);

}

void ui_DetectionN_screen_destroy(void)
{
    if(ui_DetectionN) lv_obj_del(ui_DetectionN);

    // NULL screen variables
    ui_DetectionN = NULL;
    ui_DetectionNContainer = NULL;
    ui_DetectionNLabel = NULL;
    ui_DetectionNImage = NULL;

}
