// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_DETECTIONN_H
#define UI_DETECTIONN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DetectionN

extern void ui_DetectionN_screen_init(void);
extern void ui_DetectionN_screen_destroy(void);
extern lv_obj_t * ui_DetectionN;
extern lv_obj_t * ui_DetectionNContainer;
extern lv_obj_t * ui_DetectionNLabel;
extern lv_obj_t * ui_DetectionNImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

