// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_Detection = NULL;
lv_obj_t * ui_DetectionContainer = NULL;
lv_obj_t * ui_DetectionLabel = NULL;
lv_obj_t * ui_DetectionImage = NULL;
// event funtions

// build funtions

void ui_Detection_screen_init(void)
{
    ui_Detection = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Detection, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Detection, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Detection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionContainer = lv_obj_create(ui_Detection);
    lv_obj_remove_style_all(ui_DetectionContainer);
    lv_obj_set_width(ui_DetectionContainer, 300);
    lv_obj_set_height(ui_DetectionContainer, 300);
    lv_obj_set_align(ui_DetectionContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DetectionContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DetectionContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionLabel = lv_label_create(ui_DetectionContainer);
    lv_obj_set_width(ui_DetectionLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DetectionLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DetectionLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DetectionLabel, "I am Finding you");
    lv_obj_set_style_text_color(ui_DetectionLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DetectionLabel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DetectionLabel, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionImage = lv_image_create(ui_DetectionContainer);
    lv_image_set_src(ui_DetectionImage, &ui_img_component_28_png);
    lv_obj_set_width(ui_DetectionImage, LV_SIZE_CONTENT);   /// 83
    lv_obj_set_height(ui_DetectionImage, LV_SIZE_CONTENT);    /// 87
    lv_obj_set_x(ui_DetectionImage, 86);
    lv_obj_set_y(ui_DetectionImage, -98);
    lv_obj_set_align(ui_DetectionImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DetectionImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DetectionImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_DetectionImage, 169);

}

void ui_Detection_screen_destroy(void)
{
    if(ui_Detection) lv_obj_del(ui_Detection);

    // NULL screen variables
    ui_Detection = NULL;
    ui_DetectionContainer = NULL;
    ui_DetectionLabel = NULL;
    ui_DetectionImage = NULL;

}
