// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_DETECTIONN1_H
#define UI_DETECTIONN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DetectionN1
extern void ui_DetectionN1_screen_init(void);
extern void ui_DetectionN1_screen_destroy(void);
extern lv_obj_t * ui_DetectionN1;
extern lv_obj_t * ui_DetectionN1Container;
extern lv_obj_t * ui_DetectionN1Image;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

