// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_DetectionN1 = NULL;
lv_obj_t * ui_DetectionN1Container = NULL;
lv_obj_t * ui_DetectionN1Image = NULL;
// event funtions


// build funtions

void ui_DetectionN1_screen_init(void)
{
    ui_DetectionN1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DetectionN1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DetectionN1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DetectionN1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionN1Container = lv_obj_create(ui_DetectionN1);
    lv_obj_remove_style_all(ui_DetectionN1Container);
    lv_obj_set_width(ui_DetectionN1Container, 290);
    lv_obj_set_height(ui_DetectionN1Container, 290);
    lv_obj_set_align(ui_DetectionN1Container, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DetectionN1Container, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DetectionN1Container, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_DetectionN1Container, lv_color_hex(0xE8E8E8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_DetectionN1Container, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_DetectionN1Container, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionN1Image = lv_image_create(ui_DetectionN1Container);
    lv_image_set_src(ui_DetectionN1Image, &ui_img_frame_45_png);
    lv_obj_set_width(ui_DetectionN1Image, LV_SIZE_CONTENT);   /// 331
    lv_obj_set_height(ui_DetectionN1Image, LV_SIZE_CONTENT);    /// 297
    lv_obj_set_align(ui_DetectionN1Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DetectionN1Image, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DetectionN1Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_DetectionN1Image, 159);

}

void ui_DetectionN1_screen_destroy(void)
{
    if(ui_DetectionN1) lv_obj_del(ui_DetectionN1);

    // NULL screen variables
    ui_DetectionN1 = NULL;
    ui_DetectionN1Container = NULL;
    ui_DetectionN1Image = NULL;

}
