// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_DetectionY = NULL;
lv_obj_t * ui_DetectionYImage = NULL;
lv_obj_t * ui_DetectionYLabel = NULL;
// event funtions

// build funtions

void ui_DetectionY_screen_init(void)
{
    ui_DetectionY = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_DetectionY, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DetectionY, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DetectionY, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DetectionYImage = lv_image_create(ui_DetectionY);
    lv_image_set_src(ui_DetectionYImage, &ui_img_detectionylabel_png);
    lv_obj_set_width(ui_DetectionYImage, LV_SIZE_CONTENT);   /// 149
    lv_obj_set_height(ui_DetectionYImage, LV_SIZE_CONTENT);    /// 122
    lv_obj_set_x(ui_DetectionYImage, 0);
    lv_obj_set_y(ui_DetectionYImage, -49);
    lv_obj_set_align(ui_DetectionYImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DetectionYImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_DetectionYImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DetectionYLabel = lv_label_create(ui_DetectionY);
    lv_obj_set_width(ui_DetectionYLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DetectionYLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DetectionYLabel, 0);
    lv_obj_set_y(ui_DetectionYLabel, 60);
    lv_obj_set_align(ui_DetectionYLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DetectionYLabel, " Got you.");
    lv_obj_set_style_text_color(ui_DetectionYLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DetectionYLabel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DetectionYLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DetectionYLabel, &ui_font_sfprodisplay32, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_DetectionY_screen_destroy(void)
{
    if(ui_DetectionY) lv_obj_del(ui_DetectionY);

    // NULL screen variables
    ui_DetectionY = NULL;
    ui_DetectionYImage = NULL;
    ui_DetectionYLabel = NULL;

}

void ui_DetectionY_screen_relocalize(void)
{
    // label widgets on screen

}
