// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_Light = NULL;
lv_obj_t * ui_LightContainer = NULL;
lv_obj_t * ui_LightImage = NULL;
lv_obj_t * ui_LightLabel = NULL;
// event funtions

// build funtions

void ui_Light_screen_init(void)
{
    ui_Light = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Light, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Light, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Light, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightContainer = lv_obj_create(ui_Light);
    lv_obj_remove_style_all(ui_LightContainer);
    lv_obj_set_width(ui_LightContainer, 300);
    lv_obj_set_height(ui_LightContainer, 300);
    lv_obj_set_align(ui_LightContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LightContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LightContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_LightContainer, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_LightContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LightContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightImage = lv_image_create(ui_LightContainer);
    lv_image_set_src(ui_LightImage, &ui_img_light20_png);
    lv_obj_set_width(ui_LightImage, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightImage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightImage, 0);
    lv_obj_set_y(ui_LightImage, -35);
    lv_obj_set_align(ui_LightImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LightImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LightImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LightLabel = lv_label_create(ui_LightContainer);
    lv_obj_set_x(ui_LightLabel, 0);
    lv_obj_set_y(ui_LightLabel, 42);
    lv_obj_set_align(ui_LightLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightLabel, "Brightness: 20%");
    lv_obj_set_style_text_color(ui_LightLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LightLabel, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Light_screen_destroy(void)
{
    if(ui_Light) lv_obj_del(ui_Light);

    // NULL screen variables
    ui_Light = NULL;
    ui_LightContainer = NULL;
    ui_LightImage = NULL;
    ui_LightLabel = NULL;

}

void ui_Light_screen_relocalize(void)
{
    // label widgets on screen

}
