// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_LIGHT_H
#define UI_LIGHT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Light
extern void ui_Light_screen_init(void);
extern void ui_Light_screen_destroy(void);
extern lv_obj_t * ui_Light;
extern lv_obj_t * ui_LightContainer;
extern lv_obj_t * ui_LightImage;
extern lv_obj_t * ui_LightLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

