// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_MIANYESPERSON_H
#define UI_MIANYESPERSON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MianYesPerson
extern void ui_MianYesPerson_screen_init(void);
extern void ui_MianYesPerson_screen_destroy(void);
extern lv_obj_t * ui_MianYesPerson;
extern lv_obj_t * ui_MianYesPersonImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

