// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_MianYesPerson = NULL;
lv_obj_t * ui_MianYesPersonImage = NULL;
// event funtions

// build funtions

void ui_MianYesPerson_screen_init(void)
{
    ui_MianYesPerson = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MianYesPerson, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MianYesPerson, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MianYesPerson, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MianYesPersonImage = lv_image_create(ui_MianYesPerson);
    lv_image_set_src(ui_MianYesPersonImage, &ui_img_component_8_png);
    lv_obj_set_width(ui_MianYesPersonImage, LV_SIZE_CONTENT);   /// 149
    lv_obj_set_height(ui_MianYesPersonImage, LV_SIZE_CONTENT);    /// 122
    lv_obj_set_align(ui_MianYesPersonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MianYesPersonImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MianYesPersonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_MianYesPerson_screen_destroy(void)
{
    if(ui_MianYesPerson) lv_obj_del(ui_MianYesPerson);

    // NULL screen variables
    ui_MianYesPerson = NULL;
    ui_MianYesPersonImage = NULL;

}
