// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_MORNINGANIMATION_H
#define UI_MORNINGANIMATION_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MorningAnimation
extern void ui_MorningAnimation_screen_init(void);
extern void ui_MorningAnimation_screen_destroy(void);
extern lv_obj_t * ui_MorningAnimation;
extern lv_obj_t * ui_MorningAnimationContainer;
extern lv_obj_t * ui_MorningAnimationLabel;
extern lv_obj_t * ui_MorningAnimationImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

