// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_MorningAnimation = NULL;
lv_obj_t * ui_MorningAnimationContainer = NULL;
lv_obj_t * ui_MorningAnimationLabel = NULL;
lv_obj_t * ui_MorningAnimationImage = NULL;
// event funtions

// build funtions

void ui_MorningAnimation_screen_init(void)
{
    ui_MorningAnimation = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MorningAnimation, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MorningAnimation, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MorningAnimation, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MorningAnimation, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MorningAnimationContainer = lv_obj_create(ui_MorningAnimation);
    lv_obj_remove_style_all(ui_MorningAnimationContainer);
    lv_obj_set_width(ui_MorningAnimationContainer, 290);
    lv_obj_set_height(ui_MorningAnimationContainer, 290);
    lv_obj_set_align(ui_MorningAnimationContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MorningAnimationContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MorningAnimationContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MorningAnimationContainer, lv_color_hex(0xF8F8F8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MorningAnimationContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MorningAnimationContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MorningAnimationLabel = lv_label_create(ui_MorningAnimationContainer);
    lv_obj_set_width(ui_MorningAnimationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MorningAnimationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MorningAnimationLabel, 0);
    lv_obj_set_y(ui_MorningAnimationLabel, 25);
    lv_obj_set_align(ui_MorningAnimationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MorningAnimationLabel,
                      "Good morning,Commander.\nThis is a sample briefing.\nYour real energy insights and \nmood tips will appear here after\n sleep tracking. \nwill appear here after sleep\n tracking. ");
    lv_obj_set_style_text_color(ui_MorningAnimationLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MorningAnimationLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MorningAnimationLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MorningAnimationLabel, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MorningAnimationLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MorningAnimationLabel, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MorningAnimationImage = lv_image_create(ui_MorningAnimationContainer);
    lv_image_set_src(ui_MorningAnimationImage, &ui_img_1271368945);
    lv_obj_set_width(ui_MorningAnimationImage, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_MorningAnimationImage, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_MorningAnimationImage, 0);
    lv_obj_set_y(ui_MorningAnimationImage, -90);
    lv_obj_set_align(ui_MorningAnimationImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MorningAnimationImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MorningAnimationImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_MorningAnimationImage, 169);

}

void ui_MorningAnimation_screen_destroy(void)
{
    if(ui_MorningAnimation) lv_obj_del(ui_MorningAnimation);

    // NULL screen variables
    ui_MorningAnimation = NULL;
    ui_MorningAnimationContainer = NULL;
    ui_MorningAnimationLabel = NULL;
    ui_MorningAnimationImage = NULL;

}
