// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#ifndef UI_MIANNOPERSON_H
#define UI_MIANNOPERSON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MianNoPerson

extern void ui_MianNoPerson_screen_init(void);
extern void ui_MianNoPerson_screen_destroy(void);
extern lv_obj_t * ui_MianNoPerson;
extern lv_obj_t * ui_MianNoPersonImage;
extern lv_obj_t * ui_MainHour;
extern lv_obj_t * ui_MianNoPersonLabel1;
extern lv_obj_t * ui_MainMinute;
extern lv_obj_t * ui_MianNoPersonLabel2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

