// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_MEMU_H
#define UI_MEMU_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Memu
extern void ui_Memu_screen_init(void);
extern void ui_Memu_screen_destroy(void);
extern lv_obj_t * ui_Memu;
extern lv_obj_t * ui_MemuContainer;
extern void ui_event_MueuRoller(lv_event_t * e);
extern lv_obj_t * ui_MueuRoller;
extern lv_obj_t * ui_MemuImage1;
extern lv_obj_t * ui_MemuImage2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_memu1;
extern int get_current_menu_index(void);
extern void menu_confirm_current_selection(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

