// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * uic_memu1;
lv_obj_t * ui_Memu = NULL;
lv_obj_t * ui_MemuContainer = NULL;
lv_obj_t * ui_MueuRoller = NULL;
lv_obj_t * ui_MemuImage1 = NULL;
lv_obj_t * ui_MemuImage2 = NULL;
// event funtions
void ui_event_MueuRoller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Imagezoom_Animation(ui_MemuImage2, 0);
        Imagezoom_Animation(ui_MemuImage1, 0);
    }
}

// build funtions

void ui_Memu_screen_init(void)
{
    ui_Memu = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Memu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Memu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Memu, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Memu, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemuContainer = lv_obj_create(ui_Memu);
    lv_obj_remove_style_all(ui_MemuContainer);
    lv_obj_set_width(ui_MemuContainer, 300);
    lv_obj_set_height(ui_MemuContainer, 300);
    lv_obj_set_align(ui_MemuContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MemuContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_MemuContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MueuRoller = lv_roller_create(ui_MemuContainer);
    lv_roller_set_options(ui_MueuRoller, "Wi-Fi\nWake Mode\nAlarm\nUnwind\nVolume\nScreen Brightness\nSet Time",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_MueuRoller, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_MueuRoller, 300);
    lv_obj_set_height(ui_MueuRoller, 300);
    lv_obj_set_align(ui_MueuRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MueuRoller, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_MueuRoller, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MueuRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_MueuRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_MueuRoller, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MueuRoller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MueuRoller, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_MueuRoller, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MueuRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MueuRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_MueuRoller, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_MueuRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_MueuRoller, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_MueuRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MueuRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_MueuRoller, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MueuRoller, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_MueuRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MueuRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);


    ui_MemuImage1 = lv_image_create(ui_MueuRoller);
    lv_image_set_src(ui_MemuImage1, &ui_img_vector_136_png);
    lv_obj_set_width(ui_MemuImage1, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_MemuImage1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_MemuImage1, 130);
    lv_obj_set_y(ui_MemuImage1, 0);
    lv_obj_set_align(ui_MemuImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MemuImage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MemuImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MemuImage1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MemuImage1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor(ui_MemuImage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_MemuImage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MemuImage2 = lv_image_create(ui_MueuRoller);
    lv_image_set_src(ui_MemuImage2, &ui_img_vector_136_png);
    lv_obj_set_width(ui_MemuImage2, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_MemuImage2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_MemuImage2, -130);
    lv_obj_set_y(ui_MemuImage2, 0);
    lv_obj_set_align(ui_MemuImage2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MemuImage2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MemuImage2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_MueuRoller, ui_event_MueuRoller, LV_EVENT_ALL, NULL);  
      
    
    uic_memu1 = ui_MemuContainer;

}

void ui_Memu_screen_destroy(void)
{
    if(ui_Memu) lv_obj_del(ui_Memu);

    // NULL screen variables
    ui_Memu = NULL;
    uic_memu1 = NULL;
    ui_MemuContainer = NULL;
    ui_MueuRoller = NULL;
    ui_MemuImage1 = NULL;
    ui_MemuImage2 = NULL;

}

void ui_Memu_screen_relocalize(void)
{
    // label widgets on screen

}
