// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl_start

#include "../ui.h"

lv_obj_t * ui_MianNoPerson = NULL;
lv_obj_t * ui_MianNoPersonImage = NULL;
lv_obj_t * ui_MainHour = NULL;
lv_obj_t * ui_MianNoPersonLabel1 = NULL;
lv_obj_t * ui_MainMinute = NULL;
lv_obj_t * ui_MianNoPersonLabel2 = NULL;
// event funtions

// build funtions

void ui_MianNoPerson_screen_init(void)
{
    ui_MianNoPerson = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_MianNoPerson, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MianNoPerson, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MianNoPerson, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MianNoPersonImage = lv_image_create(ui_MianNoPerson);
    lv_image_set_src(ui_MianNoPersonImage, &ui_img_component_8_png);
    lv_obj_set_width(ui_MianNoPersonImage, LV_SIZE_CONTENT);   /// 72
    lv_obj_set_height(ui_MianNoPersonImage, LV_SIZE_CONTENT);    /// 20
    lv_obj_set_x(ui_MianNoPersonImage, 0);
    lv_obj_set_y(ui_MianNoPersonImage, -70);
    lv_obj_set_align(ui_MianNoPersonImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MianNoPersonImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_MianNoPersonImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_MianNoPersonImage, 100);

    ui_MainHour = lv_label_create(ui_MianNoPerson);
    lv_obj_set_width(ui_MainHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainHour, -60);
    lv_obj_set_y(ui_MainHour, 15);
    lv_obj_set_align(ui_MainHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainHour, "06");
    lv_obj_set_style_text_color(ui_MainHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainHour, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MianNoPersonLabel1 = lv_label_create(ui_MianNoPerson);
    lv_obj_set_width(ui_MianNoPersonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MianNoPersonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MianNoPersonLabel1, 0);
    lv_obj_set_y(ui_MianNoPersonLabel1, 10);
    lv_obj_set_align(ui_MianNoPersonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MianNoPersonLabel1, ":");
    lv_obj_set_style_text_color(ui_MianNoPersonLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MianNoPersonLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MianNoPersonLabel1, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MainMinute = lv_label_create(ui_MianNoPerson);
    lv_obj_set_width(ui_MainMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MainMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MainMinute, 60);
    lv_obj_set_y(ui_MainMinute, 15);
    lv_obj_set_align(ui_MainMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MainMinute, "24");
    lv_obj_set_style_text_color(ui_MainMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MainMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MainMinute, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MianNoPersonLabel2 = lv_label_create(ui_MianNoPerson);
    lv_obj_set_width(ui_MianNoPersonLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MianNoPersonLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MianNoPersonLabel2, 0);
    lv_obj_set_y(ui_MianNoPersonLabel2, 84);
    lv_obj_set_align(ui_MianNoPersonLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MianNoPersonLabel2, "No Alarml");
    lv_obj_set_style_text_color(ui_MianNoPersonLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_MianNoPersonLabel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MianNoPersonLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_MianNoPerson_screen_destroy(void)
{
    if(ui_MianNoPerson) lv_obj_del(ui_MianNoPerson);

    // NULL screen variables
    ui_MianNoPerson = NULL;
    ui_MianNoPersonImage = NULL;
    ui_MainHour = NULL;
    ui_MianNoPersonLabel1 = NULL;
    ui_MainMinute = NULL;
    ui_MianNoPersonLabel2 = NULL;

}
