// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_nightMode = NULL;
lv_obj_t * ui_nightModeImageLeft = NULL;
lv_obj_t * ui_nightModeImageRight = NULL;
lv_obj_t * ui_nightModeHour = NULL;
lv_obj_t * ui_nightModeMinute = NULL;
lv_obj_t * ui_nightModeLabel = NULL;
lv_obj_t * ui_nightModeAlarm = NULL;
// event funtions

// build funtions

void ui_nightMode_screen_init(void)
{
    ui_nightMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_nightMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_nightMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_nightMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nightMode, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nightModeImageLeft = lv_image_create(ui_nightMode);
    lv_image_set_src(ui_nightModeImageLeft, &ui_img_nightleftwing_png);
    lv_obj_set_width(ui_nightModeImageLeft, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_nightModeImageLeft, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_nightModeImageLeft, -15);
    lv_obj_set_y(ui_nightModeImageLeft, -80);
    lv_obj_set_align(ui_nightModeImageLeft, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nightModeImageLeft, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_nightModeImageLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nightModeImageRight = lv_image_create(ui_nightMode);
    lv_image_set_src(ui_nightModeImageRight, &ui_img_nightrightwing_png);
    lv_obj_set_width(ui_nightModeImageRight, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_nightModeImageRight, LV_SIZE_CONTENT);    /// 41
    lv_obj_set_x(ui_nightModeImageRight, 15);
    lv_obj_set_y(ui_nightModeImageRight, -80);
    lv_obj_set_align(ui_nightModeImageRight, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_nightModeImageRight, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_nightModeImageRight, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_nightModeHour = lv_label_create(ui_nightMode);
    lv_obj_set_width(ui_nightModeHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nightModeHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nightModeHour, -60);
    lv_obj_set_y(ui_nightModeHour, 0);
    lv_obj_set_align(ui_nightModeHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nightModeHour, "06");
    lv_obj_set_style_text_color(ui_nightModeHour, lv_color_hex(0xA86F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nightModeHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nightModeHour, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nightModeMinute = lv_label_create(ui_nightMode);
    lv_obj_set_width(ui_nightModeMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nightModeMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nightModeMinute, 60);
    lv_obj_set_y(ui_nightModeMinute, 0);
    lv_obj_set_align(ui_nightModeMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nightModeMinute, "24");
    lv_obj_set_style_text_color(ui_nightModeMinute, lv_color_hex(0xA86F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nightModeMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nightModeMinute, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nightModeLabel = lv_label_create(ui_nightMode);
    lv_obj_set_width(ui_nightModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nightModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nightModeLabel, 0);
    lv_obj_set_y(ui_nightModeLabel, -5);
    lv_obj_set_align(ui_nightModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nightModeLabel, ":");
    lv_obj_set_style_text_color(ui_nightModeLabel, lv_color_hex(0xA86F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nightModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nightModeLabel, &ui_font_sfprodisplay45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_nightModeAlarm = lv_label_create(ui_nightMode);
    lv_obj_set_width(ui_nightModeAlarm, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_nightModeAlarm, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_nightModeAlarm, 0);
    lv_obj_set_y(ui_nightModeAlarm, 90);
    lv_obj_set_align(ui_nightModeAlarm, LV_ALIGN_CENTER);
    lv_label_set_text(ui_nightModeAlarm, "08 : 00");
    lv_obj_set_style_text_color(ui_nightModeAlarm, lv_color_hex(0xA86F2A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_nightModeAlarm, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_nightModeAlarm, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_nightMode_screen_destroy(void)
{
    if(ui_nightMode) lv_obj_del(ui_nightMode);

    // NULL screen variables
    ui_nightMode = NULL;
    ui_nightModeImageLeft = NULL;
    ui_nightModeImageRight = NULL;
    ui_nightModeHour = NULL;
    ui_nightModeMinute = NULL;
    ui_nightModeLabel = NULL;
    ui_nightModeAlarm = NULL;

}

void ui_nightMode_screen_relocalize(void)
{
    // label widgets on screen

}
