// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#ifndef UI_NETWORKBOOT_H
#define UI_NETWORKBOOT_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_NetworkBoot
extern void ui_NetworkBoot_screen_init(void);
extern void ui_NetworkBoot_screen_destroy(void);
extern lv_obj_t * ui_NetworkBoot;
extern lv_obj_t * ui_NetworkBootContainer;
extern lv_obj_t * ui_NetworkBootImage;
extern lv_obj_t * ui_NetworkBootLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

