// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#include "../ui.h"

lv_obj_t * ui_NetworkBoot = NULL;
lv_obj_t * ui_NetworkBootContainer = NULL;
lv_obj_t * ui_NetworkBootImage = NULL;
lv_obj_t * ui_NetworkBootLabel = NULL;
// event funtions

// build funtions

void ui_NetworkBoot_screen_init(void)
{
    ui_NetworkBoot = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NetworkBoot, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NetworkBoot, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NetworkBoot, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NetworkBootContainer = lv_obj_create(ui_NetworkBoot);
    lv_obj_remove_style_all(ui_NetworkBootContainer);
    lv_obj_set_width(ui_NetworkBootContainer, 290);
    lv_obj_set_height(ui_NetworkBootContainer, 290);
    lv_obj_set_align(ui_NetworkBootContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NetworkBootContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NetworkBootImage = lv_image_create(ui_NetworkBootContainer);
    lv_image_set_src(ui_NetworkBootImage, &ui_img_qrcode_png);
    lv_obj_set_width(ui_NetworkBootImage, LV_SIZE_CONTENT);   /// 200
    lv_obj_set_height(ui_NetworkBootImage, LV_SIZE_CONTENT);    /// 204
    lv_obj_set_x(ui_NetworkBootImage, 0);
    lv_obj_set_y(ui_NetworkBootImage, -40);
    lv_obj_set_align(ui_NetworkBootImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NetworkBootImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NetworkBootImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_NetworkBootLabel = lv_label_create(ui_NetworkBootContainer);
    lv_obj_set_width(ui_NetworkBootLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_NetworkBootLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_NetworkBootLabel, 0);
    lv_obj_set_y(ui_NetworkBootLabel, 60);
    lv_obj_set_align(ui_NetworkBootLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_NetworkBootLabel, " Scan to unlock more \n personalized content");
    lv_obj_set_style_text_color(ui_NetworkBootLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NetworkBootLabel, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NetworkBootLabel, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_NetworkBoot_screen_destroy(void)
{
    if(ui_NetworkBoot) lv_obj_del(ui_NetworkBoot);

    // NULL screen variables
    ui_NetworkBoot = NULL;
    ui_NetworkBootContainer = NULL;
    ui_NetworkBootImage = NULL;
    ui_NetworkBootLabel = NULL;

}

void ui_NetworkBoot_screen_relocalize(void)
{
    // label widgets on screen

}
