// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_NoiseTime = NULL;
lv_obj_t * ui_NoiseTimeContainer = NULL;
lv_obj_t * ui_NoiseTimeRoller = NULL;
lv_obj_t * ui_NoiseTimeImage1 = NULL;
lv_obj_t * ui_NoiseTimeImage = NULL;
// event funtions
void ui_event_NoiseTimeRoller(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        Imagezoom_Animation(ui_NoiseTimeImage, 0);
        Imagezoom_Animation(ui_NoiseTimeImage1, 0);
    }
}

// build funtions

void ui_NoiseTime_screen_init(void)
{
    ui_NoiseTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_NoiseTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_NoiseTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NoiseTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseTimeContainer = lv_obj_create(ui_NoiseTime);
    lv_obj_remove_style_all(ui_NoiseTimeContainer);
    lv_obj_set_width(ui_NoiseTimeContainer, 300);
    lv_obj_set_height(ui_NoiseTimeContainer, 300);
    lv_obj_set_align(ui_NoiseTimeContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_NoiseTimeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_NoiseTimeContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseTimeRoller = lv_roller_create(ui_NoiseTimeContainer);
    lv_roller_set_options(ui_NoiseTimeRoller, "off\n15 minutes\n30 minutes\n45 minutes\n60 minutes", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_NoiseTimeRoller, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_NoiseTimeRoller, 300);
    lv_obj_set_height(ui_NoiseTimeRoller, 300);
    lv_obj_set_align(ui_NoiseTimeRoller, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoiseTimeRoller, LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_NoiseTimeRoller, lv_color_hex(0x525252), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NoiseTimeRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_NoiseTimeRoller, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_NoiseTimeRoller, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NoiseTimeRoller, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NoiseTimeRoller, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_NoiseTimeRoller, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NoiseTimeRoller, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseTimeRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_NoiseTimeRoller, lv_color_hex(0x333333), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_NoiseTimeRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_NoiseTimeRoller, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_NoiseTimeRoller, lv_color_hex(0xFFFFFF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_NoiseTimeRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_NoiseTimeRoller, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_NoiseTimeRoller, &lv_font_montserrat_28, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_NoiseTimeRoller, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_NoiseTimeRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_NoiseTimeImage1 = lv_image_create(ui_NoiseTimeRoller);
    lv_image_set_src(ui_NoiseTimeImage1, &ui_img_vector_141_png);
    lv_obj_set_width(ui_NoiseTimeImage1, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_NoiseTimeImage1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_NoiseTimeImage1, 130);
    lv_obj_set_y(ui_NoiseTimeImage1, 0);
    lv_obj_set_align(ui_NoiseTimeImage1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoiseTimeImage1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NoiseTimeImage1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_image_recolor(ui_NoiseTimeImage1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_image_recolor_opa(ui_NoiseTimeImage1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_NoiseTimeImage = lv_image_create(ui_NoiseTimeRoller);
    lv_image_set_src(ui_NoiseTimeImage, &ui_img_vector_141_png);
    lv_obj_set_width(ui_NoiseTimeImage, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_NoiseTimeImage, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_NoiseTimeImage, -130);
    lv_obj_set_y(ui_NoiseTimeImage, 0);
    lv_obj_set_align(ui_NoiseTimeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_NoiseTimeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_NoiseTimeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_NoiseTimeRoller, ui_event_NoiseTimeRoller, LV_EVENT_ALL, NULL);

}

void ui_NoiseTime_screen_destroy(void)
{
    if(ui_NoiseTime) lv_obj_del(ui_NoiseTime);

    // NULL screen variables
    ui_NoiseTime = NULL;
    ui_NoiseTimeContainer = NULL;
    ui_NoiseTimeRoller = NULL;
    ui_NoiseTimeImage1 = NULL;
    ui_NoiseTimeImage = NULL;

}
