// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_NIGHTMODE_H
#define UI_NIGHTMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_nightMode
extern void ui_nightMode_screen_init(void);
extern void ui_nightMode_screen_destroy(void);
extern void ui_nightMode_screen_relocalize(void);
extern lv_obj_t * ui_nightMode;
extern lv_obj_t * ui_nightModeImageLeft;
extern lv_obj_t * ui_nightModeImageRight;
extern lv_obj_t * ui_nightModeHour;
extern lv_obj_t * ui_nightModeMinute;
extern lv_obj_t * ui_nightModeLabel;
extern lv_obj_t * ui_nightModeAlarm;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

