// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_OTA = NULL;
lv_obj_t * ui_OTALabel1 = NULL;
lv_obj_t * ui_OTALabel2 = NULL;
lv_obj_t * ui_OTASlider = NULL;
// event funtions

// build funtions

void ui_OTA_screen_init(void)
{
    ui_OTA = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_OTA, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OTA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OTA, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OTA, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OTALabel1 = lv_label_create(ui_OTA);
    lv_obj_set_width(ui_OTALabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OTALabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OTALabel1, 0);
    lv_obj_set_y(ui_OTALabel1, -25);
    lv_obj_set_align(ui_OTALabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OTALabel1, "Updating system...");
    lv_obj_set_style_text_color(ui_OTALabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OTALabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OTALabel1, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OTALabel2 = lv_label_create(ui_OTA);
    lv_obj_set_width(ui_OTALabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OTALabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OTALabel2, 0);
    lv_obj_set_y(ui_OTALabel2, 20);
    lv_obj_set_align(ui_OTALabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OTALabel2, "65%");
    lv_obj_set_style_text_color(ui_OTALabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OTALabel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OTALabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OTASlider = lv_slider_create(ui_OTA);
    lv_slider_set_value(ui_OTASlider, 65, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_OTASlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_OTASlider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_OTASlider, 170);
    lv_obj_set_height(ui_OTASlider, 5);
    lv_obj_set_x(ui_OTASlider, 0);
    lv_obj_set_y(ui_OTASlider, 41);
    lv_obj_set_align(ui_OTASlider, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_OTASlider, lv_color_hex(0x919191), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OTASlider, 100, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OTASlider, lv_color_hex(0x17C3D6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OTASlider, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_OTASlider, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OTASlider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_OTASlider, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_OTASlider,
                                                                                                lv_obj_get_style_pad_right(ui_OTASlider, LV_PART_MAIN) + 1, LV_PART_MAIN);

}

void ui_OTA_screen_destroy(void)
{
    if(ui_OTA) lv_obj_del(ui_OTA);

    // NULL screen variables
    ui_OTA = NULL;
    ui_OTALabel1 = NULL;
    ui_OTALabel2 = NULL;
    ui_OTASlider = NULL;

}
