// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-network

#include "../ui.h"

lv_obj_t * ui_OfflineMode = NULL;
lv_obj_t * ui_OfflineModeContainer = NULL;
lv_obj_t * ui_OfflineModeLabel1 = NULL;
lv_obj_t * ui_OfflineModeLabel2 = NULL;
lv_obj_t * ui_OfflineModeImage = NULL;
// event funtions

// build funtions

void ui_OfflineMode_screen_init(void)
{
    ui_OfflineMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_OfflineMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_OfflineMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_OfflineMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfflineModeContainer = lv_obj_create(ui_OfflineMode);
    lv_obj_remove_style_all(ui_OfflineModeContainer);
    lv_obj_set_width(ui_OfflineModeContainer, 290);
    lv_obj_set_height(ui_OfflineModeContainer, 290);
    lv_obj_set_align(ui_OfflineModeContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_OfflineModeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_OfflineModeContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_OfflineModeContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_OfflineModeContainer, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_OfflineModeContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfflineModeLabel1 = lv_label_create(ui_OfflineModeContainer);
    lv_obj_set_width(ui_OfflineModeLabel1, LV_SIZE_CONTENT);   /// 68
    lv_obj_set_height(ui_OfflineModeLabel1, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_OfflineModeLabel1, 0);
    lv_obj_set_y(ui_OfflineModeLabel1, 10);
    lv_obj_set_align(ui_OfflineModeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfflineModeLabel1, "Offline Mode");
    lv_obj_set_style_text_color(ui_OfflineModeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OfflineModeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OfflineModeLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OfflineModeLabel1, &ui_font_sfprodisplay20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfflineModeLabel2 = lv_label_create(ui_OfflineModeContainer);
    lv_obj_set_width(ui_OfflineModeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_OfflineModeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_OfflineModeLabel2, 0);
    lv_obj_set_y(ui_OfflineModeLabel2, 60);
    lv_obj_set_align(ui_OfflineModeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_OfflineModeLabel2, "Wake-up works with built-in\n sounds");
    lv_obj_set_style_text_color(ui_OfflineModeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_OfflineModeLabel2, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_OfflineModeLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_OfflineModeLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_OfflineModeImage = lv_image_create(ui_OfflineModeContainer);
    lv_image_set_src(ui_OfflineModeImage, &ui_img_offinternet_png);
    lv_obj_set_width(ui_OfflineModeImage, LV_SIZE_CONTENT);   /// 98
    lv_obj_set_height(ui_OfflineModeImage, LV_SIZE_CONTENT);    /// 88
    lv_obj_set_x(ui_OfflineModeImage, 0);
    lv_obj_set_y(ui_OfflineModeImage, -45);
    lv_obj_set_align(ui_OfflineModeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_OfflineModeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_OfflineModeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_OfflineMode_screen_destroy(void)
{
    if(ui_OfflineMode) lv_obj_del(ui_OfflineMode);

    // NULL screen variables
    ui_OfflineMode = NULL;
    ui_OfflineModeContainer = NULL;
    ui_OfflineModeLabel1 = NULL;
    ui_OfflineModeLabel2 = NULL;
    ui_OfflineModeImage = NULL;

}

void ui_OfflineMode_screen_relocalize(void)
{
    // label widgets on screen

}
