// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_OTA_H
#define UI_OTA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_OTA
extern void ui_OTA_screen_init(void);
extern void ui_OTA_screen_destroy(void);
extern void ui_OTA_screen_relocalize(void);
extern lv_obj_t * ui_OTA;
extern lv_obj_t * ui_OTALabel1;
extern lv_obj_t * ui_OTALabel2;
extern lv_obj_t * ui_OTASlider;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

