// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_REMINDERTOMORROW_H
#define UI_REMINDERTOMORROW_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ReminderTomorrow
extern void ui_ReminderTomorrow_screen_init(void);
extern void ui_ReminderTomorrow_screen_destroy(void);
extern void ui_ReminderTomorrow_screen_relocalize(void);
extern lv_obj_t * ui_ReminderTomorrow;
extern lv_obj_t * ui_ReminderTomorrowContainer;
extern lv_obj_t * ui_ReminderTomorrowLabel1;
extern lv_obj_t * ui_ReminderTomorrowImage;
extern lv_obj_t * ui_ReminderTomorrowLabe;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

