// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_RadarInfo = NULL;
lv_obj_t * ui_RadarInfoChart = NULL;
lv_obj_t * ui_RadarInfoChart_Xaxis = NULL;
lv_obj_t * ui_RadarInfoChart_Yaxis1 = NULL;
lv_obj_t * ui_RadarInfoChart_Yaxis2 = NULL;
lv_obj_t * ui_RadarInfoHeart = NULL;
lv_obj_t * ui_RadarInfoBreathing = NULL;
lv_obj_t * ui_RadarInfoHeartX = NULL;
lv_obj_t * ui_RadarInfoBreathingX = NULL;
// event funtions

// build funtions

void ui_RadarInfo_screen_init(void)
{
    ui_RadarInfo = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_RadarInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RadarInfo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadarInfo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarInfo, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadarInfoChart = lv_chart_create(ui_RadarInfo);
    lv_obj_set_width(ui_RadarInfoChart, 200);
    lv_obj_set_height(ui_RadarInfoChart, 180);
    lv_obj_set_align(ui_RadarInfoChart, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RadarInfoChart, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_RadarInfoChart, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_flag(ui_RadarInfoChart,
                    LV_OBJ_FLAG_OVERFLOW_VISIBLE);      //make scales visible - Should it be forced to True?
    //lv_obj_remove_flag( ui_RadarInfoChart, LV_OBJ_FLAG_SCROLLABLE );    //no chart-zoom in LVGL9 - Shouldn't it be forced to False?
    lv_chart_set_type(ui_RadarInfoChart, LV_CHART_TYPE_LINE);
    lv_chart_set_point_count(ui_RadarInfoChart, 50);
    lv_obj_set_style_bg_color(ui_RadarInfoChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RadarInfoChart, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RadarInfoChart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RadarInfoChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RadarInfoChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_color(ui_RadarInfoChart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_line_opa(ui_RadarInfoChart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadarInfoChart_Xaxis = lv_scale_create(ui_RadarInfoChart);
    lv_scale_set_mode(ui_RadarInfoChart_Xaxis, LV_SCALE_MODE_HORIZONTAL_BOTTOM);
    lv_obj_set_size(ui_RadarInfoChart_Xaxis, lv_pct(100), 50);
    lv_obj_set_align(ui_RadarInfoChart_Xaxis, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_y(ui_RadarInfoChart_Xaxis, 50 + lv_obj_get_style_pad_bottom(ui_RadarInfoChart,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_RadarInfoChart, LV_PART_MAIN));
    lv_obj_set_style_line_width(ui_RadarInfoChart_Xaxis, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Xaxis, 1, LV_PART_ITEMS);   //LVGL-9.1 ticks are thicker by default
    lv_obj_set_style_line_width(ui_RadarInfoChart_Xaxis, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_RadarInfoChart_Xaxis, 0, LV_PART_ITEMS);      //minor tick length
    lv_obj_set_style_length(ui_RadarInfoChart_Xaxis, 0, LV_PART_INDICATOR);      //major tick length
    lv_scale_set_range(ui_RadarInfoChart_Xaxis, 0, 0 > 0 ? 0 - 1 : 0);
    lv_scale_set_total_tick_count(ui_RadarInfoChart_Xaxis, (0 > 0 ? 0 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_RadarInfoChart_Xaxis, 0 >= 1 ? 0 : 1);
    ui_RadarInfoChart_Yaxis1 = lv_scale_create(ui_RadarInfoChart);
    lv_scale_set_mode(ui_RadarInfoChart_Yaxis1, LV_SCALE_MODE_VERTICAL_LEFT);
    lv_obj_set_size(ui_RadarInfoChart_Yaxis1, 50, lv_pct(100));
    lv_obj_set_align(ui_RadarInfoChart_Yaxis1, LV_ALIGN_LEFT_MID);
    lv_obj_set_x(ui_RadarInfoChart_Yaxis1, -50 - lv_obj_get_style_pad_left(ui_RadarInfoChart,
                                                                           LV_PART_MAIN) - lv_obj_get_style_border_width(ui_RadarInfoChart, LV_PART_MAIN) + 2);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis1, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis1, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis1, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_RadarInfoChart_Yaxis1, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_RadarInfoChart_Yaxis1, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_RadarInfoChart_Yaxis1, (5 > 0 ? 5 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_RadarInfoChart_Yaxis1, 0 >= 1 ? 0 : 1);
    ui_RadarInfoChart_Yaxis2 = lv_scale_create(ui_RadarInfoChart);
    lv_scale_set_mode(ui_RadarInfoChart_Yaxis2, LV_SCALE_MODE_VERTICAL_RIGHT);
    lv_obj_set_size(ui_RadarInfoChart_Yaxis2, 25, lv_pct(100));
    lv_obj_set_align(ui_RadarInfoChart_Yaxis2, LV_ALIGN_RIGHT_MID);
    lv_obj_set_x(ui_RadarInfoChart_Yaxis2, 25 + lv_obj_get_style_pad_right(ui_RadarInfoChart,
                                                                           LV_PART_MAIN) + lv_obj_get_style_border_width(ui_RadarInfoChart, LV_PART_MAIN) + 1);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis2, 0, LV_PART_MAIN);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis2, 1, LV_PART_ITEMS);
    lv_obj_set_style_line_width(ui_RadarInfoChart_Yaxis2, 1, LV_PART_INDICATOR);
    lv_obj_set_style_length(ui_RadarInfoChart_Yaxis2, 5, LV_PART_ITEMS);   //minor tick length
    lv_obj_set_style_length(ui_RadarInfoChart_Yaxis2, 10, LV_PART_INDICATOR);   //major tick length
    lv_scale_set_total_tick_count(ui_RadarInfoChart_Yaxis2, (5 > 0 ? 5 - 1 : 0) * 0 + 1);
    lv_scale_set_major_tick_every(ui_RadarInfoChart_Yaxis2, 0 >= 1 ? 0 : 1);
    lv_chart_series_t * ui_RadarInfoChart_series_1 = lv_chart_add_series(ui_RadarInfoChart, lv_color_hex(0xFF0000),
                                                                         LV_CHART_AXIS_PRIMARY_Y);
    static lv_coord_t ui_RadarInfoChart_series_1_array[] = { 0, 20, 25, 40, 75, 75, 40, 25, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
    lv_chart_set_ext_y_array(ui_RadarInfoChart, ui_RadarInfoChart_series_1, ui_RadarInfoChart_series_1_array);

    //This workaround (an invisible outline) is needed because without it chart overflow-visible doesn't work in LVGL-9.1
    lv_obj_set_style_outline_pad(ui_RadarInfoChart, LV_MAX3(50, 50, 25),
                                 LV_PART_MAIN | LV_STATE_DEFAULT);   //workaround for ineffective 'overflow visible' flag
    lv_obj_set_style_outline_width(ui_RadarInfoChart, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_RadarInfoHeart = lv_label_create(ui_RadarInfo);
    lv_obj_set_width(ui_RadarInfoHeart, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RadarInfoHeart, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RadarInfoHeart, -30);
    lv_obj_set_y(ui_RadarInfoHeart, -118);
    lv_obj_set_align(ui_RadarInfoHeart, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RadarInfoHeart, "H:");
    lv_obj_set_style_text_color(ui_RadarInfoHeart, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RadarInfoHeart, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarInfoHeart, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadarInfoBreathing = lv_label_create(ui_RadarInfo);
    lv_obj_set_width(ui_RadarInfoBreathing, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RadarInfoBreathing, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RadarInfoBreathing, -30);
    lv_obj_set_y(ui_RadarInfoBreathing, 112);
    lv_obj_set_align(ui_RadarInfoBreathing, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RadarInfoBreathing, "B:");
    lv_obj_set_style_text_color(ui_RadarInfoBreathing, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RadarInfoBreathing, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarInfoBreathing, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadarInfoHeartX = lv_label_create(ui_RadarInfo);
    lv_obj_set_width(ui_RadarInfoHeartX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RadarInfoHeartX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RadarInfoHeartX, 20);
    lv_obj_set_y(ui_RadarInfoHeartX, -118);
    lv_obj_set_align(ui_RadarInfoHeartX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RadarInfoHeartX, "xxx");
    lv_obj_set_style_text_color(ui_RadarInfoHeartX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RadarInfoHeartX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarInfoHeartX, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RadarInfoBreathingX = lv_label_create(ui_RadarInfo);
    lv_obj_set_width(ui_RadarInfoBreathingX, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RadarInfoBreathingX, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RadarInfoBreathingX, 20);
    lv_obj_set_y(ui_RadarInfoBreathingX, 112);
    lv_obj_set_align(ui_RadarInfoBreathingX, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RadarInfoBreathingX, "xxx");
    lv_obj_set_style_text_color(ui_RadarInfoBreathingX, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RadarInfoBreathingX, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RadarInfoBreathingX, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_RadarInfo_screen_destroy(void)
{
    if(ui_RadarInfo) lv_obj_del(ui_RadarInfo);

    // NULL screen variables
    ui_RadarInfo = NULL;
    ui_RadarInfoChart = NULL;
    ui_RadarInfoHeart = NULL;
    ui_RadarInfoBreathing = NULL;
    ui_RadarInfoHeartX = NULL;
    ui_RadarInfoBreathingX = NULL;

}

void ui_RadarInfo_screen_relocalize(void)
{
    // label widgets on screen

}
