// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_ReminderTomorrow = NULL;
lv_obj_t * ui_ReminderTomorrowContainer = NULL;
lv_obj_t * ui_ReminderTomorrowLabel1 = NULL;
lv_obj_t * ui_ReminderTomorrowImage = NULL;
lv_obj_t * ui_ReminderTomorrowLabe = NULL;
// event funtions

// build funtions

void ui_ReminderTomorrow_screen_init(void)
{
    ui_ReminderTomorrow = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_ReminderTomorrow, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ReminderTomorrow, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ReminderTomorrow, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReminderTomorrow, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReminderTomorrowContainer = lv_obj_create(ui_ReminderTomorrow);
    lv_obj_remove_style_all(ui_ReminderTomorrowContainer);
    lv_obj_set_width(ui_ReminderTomorrowContainer, 290);
    lv_obj_set_height(ui_ReminderTomorrowContainer, 290);
    lv_obj_set_align(ui_ReminderTomorrowContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ReminderTomorrowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_ReminderTomorrowContainer, 145, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_ReminderTomorrowContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_ReminderTomorrowContainer, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_ReminderTomorrowContainer, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReminderTomorrowLabel1 = lv_label_create(ui_ReminderTomorrowContainer);
    lv_obj_set_width(ui_ReminderTomorrowLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReminderTomorrowLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ReminderTomorrowLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReminderTomorrowLabel1, "Reminder");
    lv_obj_set_style_text_color(ui_ReminderTomorrowLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReminderTomorrowLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_ReminderTomorrowLabel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_ReminderTomorrowLabel1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_ReminderTomorrowLabel1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReminderTomorrowLabel1, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ReminderTomorrowImage = lv_image_create(ui_ReminderTomorrowContainer);
    lv_image_set_src(ui_ReminderTomorrowImage, &ui_img_bell_png);
    lv_obj_set_width(ui_ReminderTomorrowImage, LV_SIZE_CONTENT);   /// 75
    lv_obj_set_height(ui_ReminderTomorrowImage, LV_SIZE_CONTENT);    /// 76
    lv_obj_set_x(ui_ReminderTomorrowImage, 0);
    lv_obj_set_y(ui_ReminderTomorrowImage, -60);
    lv_obj_set_align(ui_ReminderTomorrowImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ReminderTomorrowImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ReminderTomorrowImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ReminderTomorrowLabe = lv_label_create(ui_ReminderTomorrowContainer);
    lv_obj_set_width(ui_ReminderTomorrowLabe, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ReminderTomorrowLabe, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ReminderTomorrowLabe, -2);
    lv_obj_set_y(ui_ReminderTomorrowLabe, 55);
    lv_obj_set_align(ui_ReminderTomorrowLabe, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ReminderTomorrowLabe, "Meeting with International\nMarketing Team at 09:30");
    lv_obj_set_style_text_color(ui_ReminderTomorrowLabe, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ReminderTomorrowLabe, 180, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ReminderTomorrowLabe, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_ReminderTomorrow_screen_destroy(void)
{
    if(ui_ReminderTomorrow) lv_obj_del(ui_ReminderTomorrow);

    // NULL screen variables
    ui_ReminderTomorrow = NULL;
    ui_ReminderTomorrowContainer = NULL;
    ui_ReminderTomorrowLabel1 = NULL;
    ui_ReminderTomorrowImage = NULL;
    ui_ReminderTomorrowLabe = NULL;

}

void ui_ReminderTomorrow_screen_relocalize(void)
{
    // label widgets on screen

}
