// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_RADARINFO_H
#define UI_RADARINFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_RadarInfo
extern void ui_RadarInfo_screen_init(void);
extern void ui_RadarInfo_screen_destroy(void);
extern void ui_RadarInfo_screen_relocalize(void);
extern lv_obj_t * ui_RadarInfo;
extern lv_obj_t * ui_RadarInfoChart;
extern lv_obj_t * ui_RadarInfoChart_Xaxis;
extern lv_obj_t * ui_RadarInfoChart_Yaxis1;
extern lv_obj_t * ui_RadarInfoChart_Yaxis2;
extern lv_obj_t * ui_RadarInfoHeart;
extern lv_obj_t * ui_RadarInfoBreathing;
extern lv_obj_t * ui_RadarInfoHeartX;
extern lv_obj_t * ui_RadarInfoBreathingX;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

