// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_sleepMode = NULL;
lv_obj_t * ui_sleepModeMoon = NULL;
lv_obj_t * ui_sleepModeHour = NULL;
lv_obj_t * ui_sleepModeMinute = NULL;
lv_obj_t * ui_sleepModeTips = NULL;
lv_obj_t * ui_sleepModeLabel = NULL;
// event funtions

// build funtions

void ui_sleepMode_screen_init(void)
{
    ui_sleepMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sleepMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sleepMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleepMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepMode, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepModeMoon = lv_image_create(ui_sleepMode);
    lv_image_set_src(ui_sleepModeMoon, &ui_img_sleepmode_png);
    lv_obj_set_width(ui_sleepModeMoon, LV_SIZE_CONTENT);   /// 43
    lv_obj_set_height(ui_sleepModeMoon, LV_SIZE_CONTENT);    /// 43
    lv_obj_set_x(ui_sleepModeMoon, 0);
    lv_obj_set_y(ui_sleepModeMoon, -70);
    lv_obj_set_align(ui_sleepModeMoon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sleepModeMoon, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_sleepModeMoon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_sleepModeHour = lv_label_create(ui_sleepMode);
    lv_obj_set_width(ui_sleepModeHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepModeHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sleepModeHour, -60);
    lv_obj_set_y(ui_sleepModeHour, 15);
    lv_obj_set_align(ui_sleepModeHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sleepModeHour, "23");
    lv_obj_set_style_text_color(ui_sleepModeHour, lv_color_hex(0xFFBB5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sleepModeHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepModeHour, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepModeMinute = lv_label_create(ui_sleepMode);
    lv_obj_set_width(ui_sleepModeMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepModeMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sleepModeMinute, 60);
    lv_obj_set_y(ui_sleepModeMinute, 15);
    lv_obj_set_align(ui_sleepModeMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sleepModeMinute, "30");
    lv_obj_set_style_text_color(ui_sleepModeMinute, lv_color_hex(0xFFBB5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sleepModeMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepModeMinute, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepModeTips = lv_label_create(ui_sleepMode);
    lv_obj_set_width(ui_sleepModeTips, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepModeTips, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sleepModeTips, 0);
    lv_obj_set_y(ui_sleepModeTips, 90);
    lv_obj_set_align(ui_sleepModeTips, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sleepModeTips, "Time for Bed");
    lv_obj_set_style_text_color(ui_sleepModeTips, lv_color_hex(0xFFBB5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sleepModeTips, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepModeTips, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepModeLabel = lv_label_create(ui_sleepMode);
    lv_obj_set_width(ui_sleepModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_sleepModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_sleepModeLabel, 0);
    lv_obj_set_y(ui_sleepModeLabel, 10);
    lv_obj_set_align(ui_sleepModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_sleepModeLabel, ":");
    lv_obj_set_style_text_color(ui_sleepModeLabel, lv_color_hex(0xFFBB5C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_sleepModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepModeLabel, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_sleepMode_screen_destroy(void)
{
    if(ui_sleepMode) lv_obj_del(ui_sleepMode);

    // NULL screen variables
    ui_sleepMode = NULL;
    ui_sleepModeMoon = NULL;
    ui_sleepModeHour = NULL;
    ui_sleepModeMinute = NULL;
    ui_sleepModeTips = NULL;
    ui_sleepModeLabel = NULL;

}

void ui_sleepMode_screen_relocalize(void)
{
    // label widgets on screen

}
