// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_SetTime = NULL;
lv_obj_t * ui_SetTimeHour = NULL;
lv_obj_t * ui_SetTimeLabel2 = NULL;
lv_obj_t * ui_SetTimeLabel1 = NULL;
lv_obj_t * ui_SetTimeImage = NULL;
lv_obj_t * ui_SetTimeMinute = NULL;
// event funtions

// build funtions

void ui_SetTime_screen_init(void)
{
    ui_SetTime = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_SetTime, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SetTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SetTime, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTime, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeHour = lv_label_create(ui_SetTime);
    lv_obj_set_width(ui_SetTimeHour, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeHour, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeHour, -60);
    lv_obj_set_y(ui_SetTimeHour, 0);
    lv_obj_set_align(ui_SetTimeHour, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeHour, "07");
    lv_obj_set_style_text_color(ui_SetTimeHour, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeHour, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeHour, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeLabel2 = lv_label_create(ui_SetTime);
    lv_obj_set_width(ui_SetTimeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeLabel2, 0);
    lv_obj_set_y(ui_SetTimeLabel2, 70);
    lv_obj_set_align(ui_SetTimeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeLabel2, "Connect to Wi-Fi \nto sync automatically");
    lv_obj_set_style_text_color(ui_SetTimeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeLabel2, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_SetTimeLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeLabel1 = lv_label_create(ui_SetTime);
    lv_obj_set_width(ui_SetTimeLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeLabel1, 0);
    lv_obj_set_y(ui_SetTimeLabel1, -85);
    lv_obj_set_align(ui_SetTimeLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeLabel1, "Local Time");
    lv_obj_set_style_text_color(ui_SetTimeLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeLabel1, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SetTimeImage = lv_image_create(ui_SetTime);
    lv_image_set_src(ui_SetTimeImage, &ui_img_800502611);
    lv_obj_set_width(ui_SetTimeImage, LV_SIZE_CONTENT);   /// 10
    lv_obj_set_height(ui_SetTimeImage, LV_SIZE_CONTENT);    /// 39
    lv_obj_set_align(ui_SetTimeImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SetTimeImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SetTimeImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_SetTimeImage, 179);

    ui_SetTimeMinute = lv_label_create(ui_SetTime);
    lv_obj_set_width(ui_SetTimeMinute, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SetTimeMinute, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SetTimeMinute, 60);
    lv_obj_set_y(ui_SetTimeMinute, 0);
    lv_obj_set_align(ui_SetTimeMinute, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SetTimeMinute, "30");
    lv_obj_set_style_text_color(ui_SetTimeMinute, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SetTimeMinute, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SetTimeMinute, &ui_font_sfprodisplay60, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_SetTime_screen_destroy(void)
{
    if(ui_SetTime) lv_obj_del(ui_SetTime);

    // NULL screen variables
    ui_SetTime = NULL;
    ui_SetTimeHour = NULL;
    ui_SetTimeLabel2 = NULL;
    ui_SetTimeLabel1 = NULL;
    ui_SetTimeImage = NULL;
    ui_SetTimeMinute = NULL;

}
