// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_SETTIME_H
#define UI_SETTIME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetTime
extern void ui_SetTime_screen_init(void);
extern void ui_SetTime_screen_destroy(void);
extern void ui_SetTime_screen_relocalize(void);
extern lv_obj_t * ui_SetTime;
extern lv_obj_t * ui_SetTimeHour;
extern lv_obj_t * ui_SetTimeLabel2;
extern lv_obj_t * ui_SetTimeLabel1;
extern lv_obj_t * ui_SetTimeImage;
extern lv_obj_t * ui_SetTimeMinute;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

