// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_SLEEPMODE_H
#define UI_SLEEPMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sleepMode
extern void ui_sleepMode_screen_init(void);
extern void ui_sleepMode_screen_destroy(void);
extern void ui_sleepMode_screen_relocalize(void);
extern lv_obj_t * ui_sleepMode;
extern lv_obj_t * ui_sleepModeMoon;
extern lv_obj_t * ui_sleepModeHour;
extern lv_obj_t * ui_sleepModeMinute;
extern lv_obj_t * ui_sleepModeTips;
extern lv_obj_t * ui_sleepModeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

