// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#ifndef UI_SLEEPDATA_H
#define UI_SLEEPDATA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_sleepData
extern void ui_sleepData_screen_init(void);
extern void ui_sleepData_screen_destroy(void);
extern lv_obj_t * ui_sleepData;
extern lv_obj_t * ui_sleepDataTitle;
extern lv_obj_t * ui_WakeWindowTitle;
extern lv_obj_t * ui_DeepSleepTitle;
extern lv_obj_t * ui_RespiratoryRateTitle;
extern lv_obj_t * ui_HeartRateTitle;
extern lv_obj_t * ui_TimeToSleepTitle;
extern lv_obj_t * ui_DurationTitle;
extern lv_obj_t * ui_SleepTimeTitle;
extern lv_obj_t * ui_sleepValue;
extern lv_obj_t * ui_WakeWindowData;
extern lv_obj_t * ui_SleepTimeData;
extern lv_obj_t * ui_DurationData;
extern lv_obj_t * ui_DeepSleepData;
extern lv_obj_t * ui_RespiratoryData;
extern lv_obj_t * ui_HeartRateData;
extern lv_obj_t * ui_TimeToSleepData;
extern lv_obj_t * ui_sleepValueImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

