// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function2

#include "../ui.h"

lv_obj_t * ui_sleepData = NULL;
lv_obj_t * ui_sleepDataTitle = NULL;
lv_obj_t * ui_WakeWindowTitle = NULL;
lv_obj_t * ui_DeepSleepTitle = NULL;
lv_obj_t * ui_RespiratoryRateTitle = NULL;
lv_obj_t * ui_HeartRateTitle = NULL;
lv_obj_t * ui_TimeToSleepTitle = NULL;
lv_obj_t * ui_DurationTitle = NULL;
lv_obj_t * ui_SleepTimeTitle = NULL;
lv_obj_t * ui_sleepValue = NULL;
lv_obj_t * ui_WakeWindowData = NULL;
lv_obj_t * ui_SleepTimeData = NULL;
lv_obj_t * ui_DurationData = NULL;
lv_obj_t * ui_DeepSleepData = NULL;
lv_obj_t * ui_RespiratoryData = NULL;
lv_obj_t * ui_HeartRateData = NULL;
lv_obj_t * ui_TimeToSleepData = NULL;
lv_obj_t * ui_sleepValueImage = NULL;
// event funtions

// build funtions

void ui_sleepData_screen_init(void)
{
    ui_sleepData = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_sleepData, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_sleepData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_sleepData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_sleepData, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepDataTitle = lv_obj_create(ui_sleepData);
    lv_obj_remove_style_all(ui_sleepDataTitle);
    lv_obj_set_width(ui_sleepDataTitle, 160);
    lv_obj_set_height(ui_sleepDataTitle, 200);
    lv_obj_set_x(ui_sleepDataTitle, -30);
    lv_obj_set_y(ui_sleepDataTitle, 0);
    lv_obj_set_align(ui_sleepDataTitle, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_sleepDataTitle, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeWindowTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_WakeWindowTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeWindowTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeWindowTitle, 0);
    lv_obj_set_y(ui_WakeWindowTitle, -60);
    lv_obj_set_align(ui_WakeWindowTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WakeWindowTitle, "Wake Window");
    lv_obj_set_style_text_color(ui_WakeWindowTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeWindowTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeWindowTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeepSleepTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_DeepSleepTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeepSleepTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DeepSleepTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeepSleepTitle, "Deep Sleep");
    lv_obj_set_style_text_color(ui_DeepSleepTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeepSleepTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DeepSleepTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RespiratoryRateTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_RespiratoryRateTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RespiratoryRateTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RespiratoryRateTitle, 0);
    lv_obj_set_y(ui_RespiratoryRateTitle, 30);
    lv_obj_set_align(ui_RespiratoryRateTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RespiratoryRateTitle, "Respiratory Rate");
    lv_obj_set_style_text_color(ui_RespiratoryRateTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RespiratoryRateTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RespiratoryRateTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_HeartRateTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateTitle, 0);
    lv_obj_set_y(ui_HeartRateTitle, 60);
    lv_obj_set_align(ui_HeartRateTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeartRateTitle, "Heart Rate");
    lv_obj_set_style_text_color(ui_HeartRateTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRateTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeartRateTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeToSleepTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_TimeToSleepTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeToSleepTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeToSleepTitle, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TimeToSleepTitle, "Time to Sleep");
    lv_obj_set_style_text_color(ui_TimeToSleepTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeToSleepTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TimeToSleepTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DurationTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_DurationTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DurationTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DurationTitle, 0);
    lv_obj_set_y(ui_DurationTitle, -30);
    lv_obj_set_align(ui_DurationTitle, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DurationTitle, "Duration");
    lv_obj_set_style_text_color(ui_DurationTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DurationTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_DurationTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SleepTimeTitle = lv_label_create(ui_sleepDataTitle);
    lv_obj_set_width(ui_SleepTimeTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SleepTimeTitle, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SleepTimeTitle, "Sleep Time");
    lv_obj_set_style_text_color(ui_SleepTimeTitle, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SleepTimeTitle, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SleepTimeTitle, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepValue = lv_obj_create(ui_sleepData);
    lv_obj_remove_style_all(ui_sleepValue);
    lv_obj_set_width(ui_sleepValue, 120);
    lv_obj_set_height(ui_sleepValue, 200);
    lv_obj_set_x(ui_sleepValue, 90);
    lv_obj_set_y(ui_sleepValue, 0);
    lv_obj_set_align(ui_sleepValue, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_sleepValue, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeWindowData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_WakeWindowData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeWindowData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeWindowData, 0);
    lv_obj_set_y(ui_WakeWindowData, -60);
    lv_obj_set_align(ui_WakeWindowData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_WakeWindowData, "07:10 - 07:20");
    lv_obj_set_style_text_color(ui_WakeWindowData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeWindowData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeWindowData, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SleepTimeData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_SleepTimeData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SleepTimeData, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_SleepTimeData, "01:10");
    lv_obj_set_style_text_color(ui_SleepTimeData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_SleepTimeData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_SleepTimeData, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DurationData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_DurationData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DurationData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DurationData, 0);
    lv_obj_set_y(ui_DurationData, -30);
    lv_obj_set_align(ui_DurationData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DurationData, "6h 05min");
    lv_obj_set_style_text_color(ui_DurationData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DurationData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DeepSleepData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_DeepSleepData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DeepSleepData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DeepSleepData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_DeepSleepData, "18%  (65min)");
    lv_obj_set_style_text_color(ui_DeepSleepData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DeepSleepData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RespiratoryData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_RespiratoryData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RespiratoryData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RespiratoryData, 0);
    lv_obj_set_y(ui_RespiratoryData, 30);
    lv_obj_set_align(ui_RespiratoryData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_RespiratoryData, "15.2 bpm");
    lv_obj_set_style_text_color(ui_RespiratoryData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RespiratoryData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeartRateData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_HeartRateData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateData, 0);
    lv_obj_set_y(ui_HeartRateData, 60);
    lv_obj_set_align(ui_HeartRateData, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeartRateData, "62 bpm (avg)  ");
    lv_obj_set_style_text_color(ui_HeartRateData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeartRateData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TimeToSleepData = lv_label_create(ui_sleepValue);
    lv_obj_set_width(ui_TimeToSleepData, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TimeToSleepData, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TimeToSleepData, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_TimeToSleepData, "18 min");
    lv_obj_set_style_text_color(ui_TimeToSleepData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TimeToSleepData, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_sleepValueImage = lv_image_create(ui_sleepValue);
    lv_image_set_src(ui_sleepValueImage, &ui_img_up_png);
    lv_obj_set_width(ui_sleepValueImage, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_sleepValueImage, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_sleepValueImage, 50);
    lv_obj_set_y(ui_sleepValueImage, 1);
    lv_obj_set_align(ui_sleepValueImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_sleepValueImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_sleepValueImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}

void ui_sleepData_screen_destroy(void)
{
    if(ui_sleepData) lv_obj_del(ui_sleepData);

    // NULL screen variables
    ui_sleepData = NULL;
    ui_sleepDataTitle = NULL;
    ui_WakeWindowTitle = NULL;
    ui_DeepSleepTitle = NULL;
    ui_RespiratoryRateTitle = NULL;
    ui_HeartRateTitle = NULL;
    ui_TimeToSleepTitle = NULL;
    ui_DurationTitle = NULL;
    ui_SleepTimeTitle = NULL;
    ui_sleepValue = NULL;
    ui_WakeWindowData = NULL;
    ui_SleepTimeData = NULL;
    ui_DurationData = NULL;
    ui_DeepSleepData = NULL;
    ui_RespiratoryData = NULL;
    ui_HeartRateData = NULL;
    ui_TimeToSleepData = NULL;
    ui_sleepValueImage = NULL;

}
