// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_UNWINDSELET_H
#define UI_UNWINDSELET_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UnwindSelet
extern void ui_UnwindSelet_screen_init(void);
extern void ui_UnwindSelet_screen_destroy(void);
extern lv_obj_t * ui_UnwindSelet;
extern lv_obj_t * ui_UnwindSeletContainer;
extern lv_obj_t * ui_UnwindSeletArc;
extern lv_obj_t * ui_UnwindSeletImage;
extern lv_obj_t * ui_UnwindSeletLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

