// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_UNWINDON_H
#define UI_UNWINDON_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UnwindOn
extern void ui_UnwindOn_screen_init(void);
extern void ui_UnwindOn_screen_destroy(void);
extern lv_obj_t * ui_UnwindOn;
extern lv_obj_t * ui_UnwindOnImage;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

