// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_UnwindSelet = NULL;
lv_obj_t * ui_UnwindSeletContainer = NULL;
lv_obj_t * ui_UnwindSeletArc = NULL;
lv_obj_t * ui_UnwindSeletImage = NULL;
lv_obj_t * ui_UnwindSeletLabel = NULL;
// event funtions

// build funtions

void ui_UnwindSelet_screen_init(void)
{
    ui_UnwindSelet = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_UnwindSelet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UnwindSelet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnwindSelet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnwindSelet, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnwindSeletContainer = lv_obj_create(ui_UnwindSelet);
    lv_obj_remove_style_all(ui_UnwindSeletContainer);
    lv_obj_set_width(ui_UnwindSeletContainer, 300);
    lv_obj_set_height(ui_UnwindSeletContainer, 300);
    lv_obj_set_align(ui_UnwindSeletContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_UnwindSeletContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_UnwindSeletContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnwindSeletArc = lv_arc_create(ui_UnwindSeletContainer);
    lv_obj_set_width(ui_UnwindSeletArc, 300);
    lv_obj_set_height(ui_UnwindSeletArc, 300);
    lv_obj_set_align(ui_UnwindSeletArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_UnwindSeletArc, 0);
    lv_arc_set_bg_angles(ui_UnwindSeletArc, 270, 269);
    lv_obj_set_style_arc_color(ui_UnwindSeletArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_UnwindSeletArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_UnwindSeletArc, lv_color_hex(0x17C3D6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_UnwindSeletArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_UnwindSeletArc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UnwindSeletArc, lv_color_hex(0x17C3D6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnwindSeletArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_UnwindSeletImage = lv_image_create(ui_UnwindSeletContainer);
    lv_image_set_src(ui_UnwindSeletImage, &ui_img_swan_png);
    lv_obj_set_width(ui_UnwindSeletImage, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_UnwindSeletImage, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_align(ui_UnwindSeletImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnwindSeletImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_UnwindSeletImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_UnwindSeletImage, 242);

    ui_UnwindSeletLabel = lv_label_create(ui_UnwindSeletContainer);
    lv_obj_set_width(ui_UnwindSeletLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UnwindSeletLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UnwindSeletLabel, 0);
    lv_obj_set_y(ui_UnwindSeletLabel, 115);
    lv_obj_set_align(ui_UnwindSeletLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UnwindSeletLabel, "Piano Drift");
    lv_obj_set_style_text_color(ui_UnwindSeletLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UnwindSeletLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnwindSeletLabel, &ui_font_sfprodisplay24, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_UnwindSelet_screen_destroy(void)
{
    if(ui_UnwindSelet) lv_obj_del(ui_UnwindSelet);

    // NULL screen variables
    ui_UnwindSelet = NULL;
    ui_UnwindSeletContainer = NULL;
    ui_UnwindSeletArc = NULL;
    ui_UnwindSeletImage = NULL;
    ui_UnwindSeletLabel = NULL;

}

void ui_UnwindSelet_screen_relocalize(void)
{
    // label widgets on screen

}
