// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_UnwindOn = NULL;
lv_obj_t * ui_UnwindOnImage = NULL;
// event funtions

// build funtions

void ui_UnwindOn_screen_init(void)
{
    ui_UnwindOn = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_UnwindOn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_UnwindOn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UnwindOn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UnwindOn, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UnwindOnImage = lv_image_create(ui_UnwindOn);
    lv_image_set_src(ui_UnwindOnImage, &ui_img_swan_1_png);
    lv_obj_set_width(ui_UnwindOnImage, LV_SIZE_CONTENT);   /// 360
    lv_obj_set_height(ui_UnwindOnImage, LV_SIZE_CONTENT);    /// 360
    lv_obj_set_align(ui_UnwindOnImage, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UnwindOnImage, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_UnwindOnImage, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_scale(ui_UnwindOnImage, 220);

}

void ui_UnwindOn_screen_destroy(void)
{
    if(ui_UnwindOn) lv_obj_del(ui_UnwindOn);

    // NULL screen variables
    ui_UnwindOn = NULL;
    ui_UnwindOnImage = NULL;

}
