// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_VOLUME__H
#define UI_VOLUME__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Volume_
extern void ui_Volume__screen_init(void);
extern void ui_Volume__screen_destroy(void);
extern lv_obj_t * ui_Volume_;
extern lv_obj_t * ui_VolumeContainer;
extern lv_obj_t * ui_VolumeArc;
extern lv_obj_t * ui_VolumeImage;
extern lv_obj_t * ui_VolumeLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

