// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_WAKEMODETEST_H
#define UI_WAKEMODETEST_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WakeModeTest
extern void ui_WakeModeTest_screen_init(void);
extern void ui_WakeModeTest_screen_destroy(void);
extern void ui_WakeModeTest_screen_relocalize(void);
extern void ui_event_WakeModeTest(lv_event_t * e);
extern lv_obj_t * ui_WakeModeTest;
extern lv_obj_t * ui_WakeModeTestContainer1;
extern lv_obj_t * ui_WakeModeTest2;
extern lv_obj_t * ui_WakeModeTest1;
extern void ui_event_WakeModeTestContainer2(lv_event_t * e);
extern lv_obj_t * ui_WakeModeTestContainer2;
extern lv_obj_t * ui_WakeModeTestLabel1;
extern lv_obj_t * ui_WakeModeTestLabel2;
extern lv_obj_t * ui_WakeModeTestContainer3;
extern lv_obj_t * ui_WakeModeTestLabel3;
extern lv_obj_t * ui_WakeModeTestLabel4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

