// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_WakeModeTest = NULL;
lv_obj_t * ui_WakeModeTestContainer1 = NULL;
lv_obj_t * ui_WakeModeTest2 = NULL;
lv_obj_t * ui_WakeModeTest1 = NULL;
lv_obj_t * ui_WakeModeTestContainer2 = NULL;
lv_obj_t * ui_WakeModeTestLabel1 = NULL;
lv_obj_t * ui_WakeModeTestLabel2 = NULL;
lv_obj_t * ui_WakeModeTestContainer3 = NULL;
lv_obj_t * ui_WakeModeTestLabel3 = NULL;
lv_obj_t * ui_WakeModeTestLabel4 = NULL;

// event funtions
void ui_event_WakeModeTest(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        memuDown_Animation(ui_WakeModeTestContainer2, 0); // 向上滑动手势触发向下菜单移动
    }
    if(event_code == LV_EVENT_GESTURE && lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        memuUp_Animation(ui_WakeModeTestContainer2, 0); // 向下滑动手势触发向上菜单移动
    }
}

void ui_event_WakeModeTestContainer2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        // 屏幕加载时的处理
    }
}

// build funtions

void ui_WakeModeTest_screen_init(void)
{
    ui_WakeModeTest = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WakeModeTest, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WakeModeTest, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WakeModeTest, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeTest, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeTestContainer1 = lv_obj_create(ui_WakeModeTest);
    lv_obj_remove_style_all(ui_WakeModeTestContainer1);
    lv_obj_set_width(ui_WakeModeTestContainer1, 300);
    lv_obj_set_height(ui_WakeModeTestContainer1, 300);
    lv_obj_set_align(ui_WakeModeTestContainer1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WakeModeTestContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WakeModeTestContainer1, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_WakeModeTestContainer1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeTest2 = lv_image_create(ui_WakeModeTestContainer1);
    lv_image_set_src(ui_WakeModeTest2, &ui_img_vector_136_png);
    lv_obj_set_width(ui_WakeModeTest2, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_WakeModeTest2, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_WakeModeTest2, -130);
    lv_obj_set_y(ui_WakeModeTest2, 0);
    lv_obj_set_align(ui_WakeModeTest2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WakeModeTest2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WakeModeTest2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeModeTest1 = lv_image_create(ui_WakeModeTestContainer1);
    lv_image_set_src(ui_WakeModeTest1, &ui_img_vector_136_png);
    lv_obj_set_width(ui_WakeModeTest1, LV_SIZE_CONTENT);   /// 49
    lv_obj_set_height(ui_WakeModeTest1, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_WakeModeTest1, 130);
    lv_obj_set_y(ui_WakeModeTest1, 0);
    lv_obj_set_align(ui_WakeModeTest1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WakeModeTest1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_WakeModeTest1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeModeTestContainer2 = lv_obj_create(ui_WakeModeTest);
    lv_obj_remove_style_all(ui_WakeModeTestContainer2);
    lv_obj_set_width(ui_WakeModeTestContainer2, 200);
    lv_obj_set_height(ui_WakeModeTestContainer2, 60);
    lv_obj_set_align(ui_WakeModeTestContainer2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WakeModeTestContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeModeTestLabel1 = lv_label_create(ui_WakeModeTestContainer2);
    lv_obj_set_width(ui_WakeModeTestLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeTestLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeTestLabel1, 0);
    lv_obj_set_y(ui_WakeModeTestLabel1, -15);
    lv_obj_set_align(ui_WakeModeTestLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeTestLabel1, "Rhythm");
    lv_obj_set_style_text_color(ui_WakeModeTestLabel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeTestLabel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeTestLabel1, &ui_font_sfprodisplay36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeTestLabel2 = lv_label_create(ui_WakeModeTestContainer2);
    lv_obj_set_width(ui_WakeModeTestLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeTestLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeTestLabel2, 0);
    lv_obj_set_y(ui_WakeModeTestLabel2, 20);
    lv_obj_set_align(ui_WakeModeTestLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeTestLabel2, " Fixed wake-up Alarm\n");
    lv_obj_set_style_text_color(ui_WakeModeTestLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeTestLabel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeTestLabel2, &ui_font_sfprodisplay14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeTestContainer3 = lv_obj_create(ui_WakeModeTest);
    lv_obj_remove_style_all(ui_WakeModeTestContainer3);
    lv_obj_set_width(ui_WakeModeTestContainer3, 200);
    lv_obj_set_height(ui_WakeModeTestContainer3, 70);
    lv_obj_set_x(ui_WakeModeTestContainer3, 0);
    lv_obj_set_y(ui_WakeModeTestContainer3, 80);
    lv_obj_set_align(ui_WakeModeTestContainer3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WakeModeTestContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WakeModeTestLabel3 = lv_label_create(ui_WakeModeTestContainer3);
    lv_obj_set_width(ui_WakeModeTestLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeTestLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeTestLabel3, 0);
    lv_obj_set_y(ui_WakeModeTestLabel3, -15);
    lv_obj_set_align(ui_WakeModeTestLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeTestLabel3, "Recovery");
    lv_obj_set_style_text_color(ui_WakeModeTestLabel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeTestLabel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeTestLabel3, &ui_font_sfprodisplay36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeTestLabel4 = lv_label_create(ui_WakeModeTestContainer3);
    lv_obj_set_width(ui_WakeModeTestLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeTestLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeTestLabel4, 0);
    lv_obj_set_y(ui_WakeModeTestLabel4, 20);
    lv_obj_set_align(ui_WakeModeTestLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeTestLabel4, "No alarm - sleep tracking \non, greeting on wake.");
    lv_obj_set_style_text_color(ui_WakeModeTestLabel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeTestLabel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WakeModeTestLabel4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeTestLabel4, &ui_font_sfprodisplay14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_WakeModeTestContainer2, ui_event_WakeModeTestContainer2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WakeModeTest, ui_event_WakeModeTest, LV_EVENT_ALL, NULL);

}

void ui_WakeModeTest_screen_destroy(void)
{
    if(ui_WakeModeTest) lv_obj_del(ui_WakeModeTest);

    // NULL screen variables
    ui_WakeModeTest = NULL;
    ui_WakeModeTestContainer1 = NULL;
    ui_WakeModeTest2 = NULL;
    ui_WakeModeTest1 = NULL;
    ui_WakeModeTestContainer2 = NULL;
    ui_WakeModeTestLabel1 = NULL;
    ui_WakeModeTestLabel2 = NULL;
    ui_WakeModeTestContainer3 = NULL;
    ui_WakeModeTestLabel3 = NULL;
    ui_WakeModeTestLabel4 = NULL;

}

void ui_WakeModeTest_screen_relocalize(void)
{
    // label widgets on screen

}
