// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"

lv_obj_t * ui_WakeMode = NULL;
lv_obj_t * ui_WakeModeContainer = NULL;
lv_obj_t * ui_WakeModeLabel = NULL;
lv_obj_t * ui_WakeModeLabel2 = NULL;
lv_obj_t * ui_WakeModeArc = NULL;
// event funtions

// build funtions

void ui_WakeMode_screen_init(void)
{
    ui_WakeMode = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_WakeMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WakeMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WakeMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeMode, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeContainer = lv_obj_create(ui_WakeMode);
    lv_obj_remove_style_all(ui_WakeModeContainer);
    lv_obj_set_width(ui_WakeModeContainer, 300);
    lv_obj_set_height(ui_WakeModeContainer, 300);
    lv_obj_set_align(ui_WakeModeContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WakeModeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WakeModeContainer, 150, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeLabel = lv_label_create(ui_WakeModeContainer);
    lv_obj_set_width(ui_WakeModeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeLabel, 0);
    lv_obj_set_y(ui_WakeModeLabel, -30);
    lv_obj_set_align(ui_WakeModeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeLabel, "Smart ");
    lv_obj_set_style_text_color(ui_WakeModeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeLabel, &ui_font_sfprodisplay45, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeLabel2 = lv_label_create(ui_WakeModeContainer);
    lv_obj_set_width(ui_WakeModeLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WakeModeLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WakeModeLabel2, 0);
    lv_obj_set_y(ui_WakeModeLabel2, 30);
    lv_obj_set_align(ui_WakeModeLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WakeModeLabel2, "Wakes you gently, based \non your sleep cycle.");
    lv_obj_set_style_text_color(ui_WakeModeLabel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WakeModeLabel2, 170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WakeModeLabel2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WakeModeLabel2, &ui_font_sfprodisplay18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WakeModeArc = lv_arc_create(ui_WakeModeContainer);
    lv_obj_set_width(ui_WakeModeArc, 300);
    lv_obj_set_height(ui_WakeModeArc, 300);
    lv_obj_set_x(ui_WakeModeArc, -1);
    lv_obj_set_y(ui_WakeModeArc, 0);
    lv_obj_set_align(ui_WakeModeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_WakeModeArc, 0);
    lv_arc_set_bg_angles(ui_WakeModeArc, 270, 269);
    lv_obj_set_style_arc_color(ui_WakeModeArc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WakeModeArc, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_WakeModeArc, lv_color_hex(0x17C3D6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_WakeModeArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_WakeModeArc, 7, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_WakeModeArc, lv_color_hex(0x17C3D6), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WakeModeArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_WakeMode_screen_destroy(void)
{
    if(ui_WakeMode) lv_obj_del(ui_WakeMode);

    // NULL screen variables
    ui_WakeMode = NULL;
    ui_WakeModeContainer = NULL;
    ui_WakeModeLabel = NULL;
    ui_WakeModeLabel2 = NULL;
    ui_WakeModeArc = NULL;

}
