// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#ifndef UI_WAKEMODE_H
#define UI_WAKEMODE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WakeMode
extern void ui_WakeMode_screen_init(void);
extern void ui_WakeMode_screen_destroy(void);
extern lv_obj_t * ui_WakeMode;
extern lv_obj_t * ui_WakeModeContainer;
extern lv_obj_t * ui_WakeModeLabel;
extern lv_obj_t * ui_WakeModeLabel2;
extern lv_obj_t * ui_WakeModeArc;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

