// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"


extern const uint8_t _binary_ui_img_800502611_bin_start[];
extern const uint8_t _binary_ui_img_800502611_bin_end[];

// IMAGE DATA: assets/：.png
lv_image_dsc_t ui_img_800502611 = {
    .header.w = 5,
    .header.h = 24,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_800502611_load()
{
    ui_img_800502611.data = UI_LOAD_IMAGE(
        _binary_ui_img_800502611_bin_start,
        (uint32_t)(_binary_ui_img_800502611_bin_end - _binary_ui_img_800502611_bin_start),
        360);
    ui_img_800502611.data_size = 360;
}
