// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"


extern const uint8_t _binary_ui_img_detectionn1image_png_bin_start[];
extern const uint8_t _binary_ui_img_detectionn1image_png_bin_end[];

// IMAGE DATA: assets/DetectionN1Image.png
lv_image_dsc_t ui_img_detectionn1image_png = {
    .header.w = 146,
    .header.h = 120,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_detectionn1image_png_load()
{
    ui_img_detectionn1image_png.data = UI_LOAD_IMAGE(
        _binary_ui_img_detectionn1image_png_bin_start,
        (uint32_t)(_binary_ui_img_detectionn1image_png_bin_end - _binary_ui_img_detectionn1image_png_bin_start),
        52560);
    ui_img_detectionn1image_png.data_size = 52560;
}
