// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: lvgl-function1

#include "../ui.h"


extern const uint8_t _binary_ui_img_sun_png_bin_start[];
extern const uint8_t _binary_ui_img_sun_png_bin_end[];

// IMAGE DATA: assets/Sun.png
lv_image_dsc_t ui_img_sun_png = {
    .header.w = 48,
    .header.h = 48,
    .header.cf = LV_COLOR_FORMAT_NATIVE_WITH_ALPHA,
    .header.magic = LV_IMAGE_HEADER_MAGIC,
};

void ui_img_sun_png_load()
{
    ui_img_sun_png.data = UI_LOAD_IMAGE(
        _binary_ui_img_sun_png_bin_start,
        (uint32_t)(_binary_ui_img_sun_png_bin_end - _binary_ui_img_sun_png_bin_start),
        6912);
    ui_img_sun_png.data_size = 6912;
}
